### ISSUE TITLE
FR: Automatically Suggest Sentence Completions

### ISSUE THREAD

**Issue by chrisgrieser** [nhaouari/obsidian-textgenerator-plugin#100]
So as opposed to the _on-demand_ suggestions currently offered by this plug, AI-generated text could also be suggested automatically via [`EditorSuggest`](https://marcus.se.net/obsidian-plugin-docs/reference/typescript/classes/EditorSuggest). From a few weeks of trying out various AI plugins in the code editor, I found them to be actually more useful than manually prompting GPT.

Take this example from using OpenAI in neovim, where it completes a sentence without me prompting it to do so:
![CleanShot 2023-02-28 at 15 07 44](https://user-images.githubusercontent.com/73286100/221879071-21cadbc0-69d3-4551-9b15-12b7074ca744.png)

As such a feature would require a high number of API calls, it should probably be restricted to a lower number of tokens per call. In my view, only completing a sentence might make most sense.

**Comment by nhaouari** [comment]
Could you please check the last version 0.2.5 of the plugin? 
![image](https://user-images.githubusercontent.com/9850722/222751643-aaff4c88-38ac-40d6-8efd-c254c5123c36.png)

**Comment by chrisgrieser** [comment]
Thanks for the quick implementation 🥳 

A few bugs/issues with the implementation
- When using auto-suggest with a model that is not gpt-3.5-turbo, it fails. (Why not automatically use gpt-3.5-turbo for autosuggest then?)
- When accepting a completion, the cursor is one position *left* from the end of the line, which is a bit annoying.
- When we are doing sentence completions already, the plugin might as well append a `. ` (dot and space) to the completions?
- The three spaces as trigger character for auto-suggest is an interesting choice, but having it by default is very problematic, since it's not recognizable in the UI. I was wondering why autosuggest did not work, until I realized that there was more than one space in that text field
- While the spinning fidget that the plugin is loading is quite handy, when using autosuggests it's a very annoying and gets in the way of typing a lot.
- `tab` should move you to the next suggestions, like we are used to from many code editors already

---

Generally, I think a full auto-suggest might be useful:
- Instead of relying on the user typing a a certain trigger, I'd rather use one space as trigger character (end of word) and truly make it an **auto**-suggestion. 
- A relevant option might be to only trigger the request after a certain amount of idle time  to avoid unnecessary requests when the user is typing. Maybe 200-500ms delay (potentially make this an adjustable option)
- Have a command for toggling auto-suggestions on and off, without the need to reload the plugin

**Comment by nhaouari** [comment]
Thank you @chrisgrieser for your feedback and for bringing those issues to my attention. 

I have implemented all the changes you suggested, and we would love to hear your thoughts on the new version v0.2.7 #106 . 

Is there anything else you would like to see improved or added? 

Your input helps us make the plugin better for everyone who uses it. 

Thank you again for your valuable feedback!

> chrisgrieser

**Comment by chrisgrieser** [comment]
Wow, thank you! looks smooth to me so far. 

Ok, some minor issues left:
- analogue to `tab` going to the next suggestion, `shift-tab` should go to the previous one
- maybe an (optional) statusbar item for autosuggestions. It could show three states:
  1. autosuggestions off
  2. autosuggestions on
  3. autosuggestions on & currently query (this one would especially make sense since now without the spinner, it's a bit hard to tell whether the plugin is currently active or not.)
- could you explain what exactly the `stop phrase` option does or more generally, what a stop phrase is?

**Comment by nhaouari** [comment]
Thank you for your feedback @chrisgrieser ! I'm glad to hear that the plugin is working smoothly for you so far. 

Regarding your suggestions, I will work on implementing the `shift-tab` functionality to go to the previous suggestion and adding an optional status bar item for autosuggestions. I agree that it would be helpful to have a clear indicator of whether the plugin is currently active or not.

As for the stop phrase option, this is a way to signal to the model generating the text when you want it to stop generating text. It could be a character like a space or period, or even a line break. This can be useful in auto suggestion when you want to complete by words (using space ` ` as a stop phrase), sentences (using dot `.` as a stop phrase), or paragraphs (using line break `\n` as a stop phrase).

Thank you again for your feedback and suggestions!

**Comment by nhaouari** [comment]
@chrisgrieser 
## Release v0.2.10: Text Generator Plugin

### Enhancements

- Improved the user experience by adding `shift-tab` functionality to move to the previous suggestion when using auto-suggestions.
- Added an optional statusbar item for autosuggestions that displays the status of auto-suggest and if it is currently querying.

### Bug Fixes

- Fixed a bug where debugging through debug module from console was not working properly. 
The follwing command in console shows all the logs of the plugin
```
localStorage.debug = 'text*'
```

**Comment by chrisgrieser** [comment]
Fantastic, thank you <3
I'll close this since I cannot think of anything to improve rn :)

**Comment by chrisgrieser** [comment]
sorry, two minor visual issues I still noticed:
- in the `EditorSuggest`, it seems it is missing the dot at the end of the sentences (they get inserted correctly, but are not displayed there,  it's only a minor)
- The status bar items only shows if auto-suggest is on or not, but it does not show whether a query is currently being processed

**Comment by nhaouari** [comment]
Thank you @chrisgrieser  for bringing these visual issues to my attention. 
Could you please provide us with more details on how to reproduce the missing dot issue in `EditorSuggest`? 
this will help me identify and fix the issue more efficiently.

Regarding the status bar items, I appreciate your feedback. I currently show processing status in two places as shown in the attached images. However, if you have any suggestions to make it better, we would be glad to hear them. Thank you for your valuable input!
![image](https://user-images.githubusercontent.com/9850722/222979211-9de1b256-6b9e-4d86-b56f-1447d0068afd.png)
![image](https://user-images.githubusercontent.com/9850722/222979216-0fd98851-afe6-4d16-aca6-1a2d64136e44.png)

**Comment by chrisgrieser** [comment]
The fidget only shows up if you have the general status bar icon enabled. Since I have disabled it, and only have the auto-suggest icon enabled, the fidget does not appear for me. How about making one unified status bar item that indicates:
- max tokens
- auto-suggest status
- whether text generator is currently processing (= the fidget)

I'd also drop "Text generator" and "AUTO-SUGGEST" since they take up a lot of space. Instead, the [lucide robot icon](https://lucide.dev/?search=ai) maybe? and a tooltip on hover that it represents the text generator plugin? that's how most other plugins do it; it saves space but still conveys the information.

---

here in this image you can see that in the eidtorsuggest, it does not show the dots at the end of a sentence (I am using `.` as stop phrase, in case that matters)
![Screenshot 2023-03-06 at 11 22 52](https://user-images.githubusercontent.com/73286100/223083587-dc49d9e8-a03e-4754-a301-6528df520ef6.png)

**Comment by nhaouari** [comment]
Hi @chrisgrieser,  I wanted to let you know that I have taken your suggestions into consideration and implemented them in the latest version (v0.2.14). 
Thank you for your feedback.

**Comment by chrisgrieser** [comment]
there is a small extra gap
![CleanShot 2023-03-06 at 20 24 06](https://user-images.githubusercontent.com/73286100/223210353-9c6f5f99-d487-4a4e-9e82-13aa392d3f41.png)

the cause is this `margin-right`
![CleanShot 2023-03-06 at 20 23 08](https://user-images.githubusercontent.com/73286100/223210212-a0d93b6a-7044-4a7a-8605-9c48aad7532b.png)

---

also, I think displaying the tokens as thousands ("0.2k" instead of "200") might be confusing to some people, and also a bit unnecessary since most people will use a token number smaller than 1000. At least, I'd not abbreviate the token number value when it's lower than 1000 tokens

**Comment by chrisgrieser** [comment]
okay, think now pretty much everything regarding this feature has been fixed/implemented for now. if there comes up sth new, I'll open a new issue, this once can be checked off I think!
