### ISSUE TITLE
Report errors

### ISSUE THREAD

**Issue by niecailong** [nhaouari/obsidian-textgenerator-plugin#103]
![image](https://user-images.githubusercontent.com/75868761/222613906-95dc9716-0359-47c5-aae0-6b3c8010edb4.png)

**Comment by niecailong** [comment]
> [!failure]- Failure 
>   Error: net::ERR_CONNECTION_TIMED_OUT
>   
>   - browser_init:101 SimpleURLLoaderWrapper.
>     node:electron/js2c/browser_init:101:7169
>   
>   - node:events:390 SimpleURLLoaderWrapper.emit
>     node:events:390:28
>   
>

**Comment by nhaouari** [comment]
Hi @niecailong ,

Sorry to hear that you're facing an issue with Text Generator.  I'd recommend opening your OpenAI account on your PC and checking the console for any error messages. You can also try typing localStorage.debug="textGenerator*" in the console to see the log messages and get a better understanding of what's causing the error.

Hopefully, this will help you identify and fix the issue. Let me know if you need any further assistance.

Good luck

**Comment by nhaouari** [comment]
I would like to suggest that you check the most recent version of the plugin, which is v0.3.1, as it features improved error messages that are more expressive. This update could enhance the overall performance and user experience of the plugin, and may provide helpful insights in the event of any issues that arise.
