### ISSUE TITLE
Autocomplete doesn't work in lines with text

### ISSUE THREAD

**Issue by ShravanSunder** [nhaouari/obsidian-textgenerator-plugin#104]
Autocomplete only works on new lines with no text in front of the phrase

**Comment by nhaouari** [comment]
Hey @ShravanSunder !

Thanks for bringing this issue to our attention. We actually just released version 0.2.9, which includes several bug fixes and improvements.

Let us know if you're still experiencing any issues after updating.

**Comment by ShravanSunder** [comment]
I just updated, still having same issues, will try to update video

**Comment by ShravanSunder** [comment]
https://user-images.githubusercontent.com/5294949/224703470-03514e73-b1d9-489c-9e19-696046f48c26.mp4

**Comment by nhaouari** [comment]
The issue may arise due to the presence of special characters in the regular expression used it the trigger phrase. 

As a temporary solution, you can modify the trigger string by replacing it with double or triple spaces until a permanent fix is implemented.

**Comment by nhaouari** [comment]
@ShravanSunder  In the latest version of plugin, the mentioned bug  has been fixed. 

https://user-images.githubusercontent.com/9850722/234214211-da17c6c6-b361-40e3-afee-149b731a16b7.mp4
