### ISSUE TITLE
Error: Request failed, status 400

### ISSUE THREAD

**Issue by avataraustin** [nhaouari/obsidian-textgenerator-plugin#105]
<img width="283" alt="Screenshot 2023-03-04 at 1 52 19 PM" src="https://user-images.githubusercontent.com/39737076/222926580-4c3f20cd-5eed-415b-859b-9f5a0fdd5477.png">

### It was working fine and then the above error.
- updated to latest version of tg
- verified openai account in good standing
- checked openai api status is up
- restarted obsidian

Ideas on what to do next?

**Comment by nhaouari** [comment]
Hi @avataraustin,

Sorry to hear that you're facing an issue with the text generator. Based on the information you've provided, it seems like you've already done all the necessary checks to ensure that everything is in order.

However, I'd recommend opening your OpenAI account on your PC and checking the console for any error messages. You can also try typing `localStorage.debug="textGenerator*"` in the console to see the log messages and get a better understanding of what's causing the error.

Hopefully, this will help you identify and fix the issue. Let me know if you need any further assistance.

Good luck

**Comment by avataraustin** [comment]
Ok, so I have some new info to report.  I was able to get TG to start generating again by selecting text and then CMD+J  generating, whereas before I was able to generate text just by having my cursor at the end of the paragraph and telling it to generate. If I try that now, I get the error. I can bypass the error by dragging and selecting empty line(s) and then telling it to generate. As long as something (even nothing) is actually selected it will generate.

**Comment by aarons** [comment]
Hi @nhaouari, I consistently run into this error as well. It happens anytime there are more than 1000 tokens sent in the context.

It's reproducible using all the generate text commands in a note with more than 1000 tokens of words:

- Generate Text!
- Generate Text (use Metadata))!
- Templates: Generate and Insert!

I have max_tokens set to 3000 in the plugin options. I also tried overwriting the setting in the frontmatter to 4000 for one note to see if that would work. But I still got the same error.

I appreciate all your work on this plugin, it's been tremendous having GPT models available for collaboration in my notes.

**Comment by nhaouari** [comment]
make sure that the token count of your prompt plus max_tokens cannot exceed the model's context length. Most models have a context length of 2048 tokens (except for the newest models , which support 4096).

![image](https://user-images.githubusercontent.com/9850722/216415902-039810ba-2675-4d2a-86c5-6073b5bb8e13.png)

https://platform.openai.com/docs/api-reference/completions

**Comment by aarons** [comment]
Maybe I'm misunderstanding something. The API call fails as soon as the `prompt_token` count passes 1000, regardless of the max_token configured in the settings.

So in the below example, I'm using `gpt-3.5-turbo-0301` and have max_tokens set to 3000 in the plugin options. The first two requests are slightly under 1000 prompt_tokens, and the total response should still be well under the models context limit. The third request is slightly over 1000 prompt_tokens, which throws an error.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/54643/223808596-08ab2e56-be33-4d3b-a68d-0de3e881e170.png">

**Comment by nhaouari** [comment]
If the sum of prompt_tokens and max_tokens exceeds the maximum request size, the request will fail before the generation process.

**Comment by nhaouari** [comment]
To get a better understanding of how it works, you can test it out on the OpenAI playground.

**Comment by aarons** [comment]
OH! Facepalm. Ok that makes sense.

I was thinking that max_tokens was a limit for any given api call, and that context (prompt_tokens) were subtracted from max_tokens, so that the model would only answer utilizing whatever tokens were left.

I think it would be safe to close this ticket. If I can think of a clear way to describe how this works I may submit a PR for the docs.
