### ISSUE TITLE
Version 0.2.10 missing main.js

### ISSUE THREAD

**Issue by johnthomas00** [nhaouari/obsidian-textgenerator-plugin#107]
I get this error when trying to install current latest version 0.2.10, released 45 minutes ago.

app.js:1 Plugin failure: obsidian-textgenerator-plugin Error: ENOENT: no such file or directory, open '[redacted]\.obsidian\plugins\obsidian-textgenerator-plugin\main.js'

**Comment by 320187240** [comment]
I have the same problem

**Comment by nhaouari** [comment]
I have added main.js
