### ISSUE TITLE
Incorrect spelling: "stared" -> "starred"

### ISSUE THREAD

**Issue by Lknechtli** [nhaouari/obsidian-textgenerator-plugin#108]
Stared simple past tense and past participle of stare (as in, to stare at an object), starred is the simple past tense and past participle of star (as in, to annotate a heading with a star).

The usage seems consistent, so it should be a simple search/replace.

**Comment by nhaouari** [comment]
Thank you very much for bringing this to our attention. We appreciate your feedback and have made the necessary changes to ensure consistency in our language usage. Your contribution helps us improve the quality of our content and we are grateful for it.
