### ISSUE TITLE
android: no update and no install possible since today

### ISSUE THREAD

**Issue by merlinuwe** [nhaouari/obsidian-textgenerator-plugin#109]
As the title says.

Hangs on update and hangs on install.

Xiaomi Poco 3 Pro.

**Comment by nhaouari** [comment]
Try to reinstall the plugin.

**Comment by merlinuwe** [comment]
Before your suggestion: Uninstalling does not work or takes too long time. I deleted the folder from the file system.

(Side effect while the plugin was installed: I could not make a new note.)

**Comment by merlinuwe** [comment]
Obsidian was very slowly in doing something (add a note, delete a note, install a plugin). Now the problems are gone. You can delete this issue or mark is as solved. 

Nonetheless: Thanks for your fast response!
