### ISSUE TITLE
Custom template where context is not at the beginning

### ISSUE THREAD

**Issue by mrektor** [nhaouari/obsidian-textgenerator-plugin#110]
I'm doing a prompt template like this: 

---
PromptInfo:
 promptId: fix grammar
 name: 🗞️fix grammar
 description: fix the grammar of the text
 required_values: 
 author: 
 tags: 
 version: 0.0.1
---
This grammar converter is a program checks the text for incorrect grammar, spelling, and punctuation, and then corrects it accordingly. The grammar converter also has a built-in dictionary to help locate and correct any unfamiliar words. 

INPUT: {{context}}
OUTPUT:

But when I highlight some text and then use it, it put the output before the highlighted text. Could it be because it expects the {{context}} to be at the beginning? Can this be fixed? that would allow to create more expressive prompts and would increase usability.

**Comment by nhaouari** [comment]
use {{selection}}
