### ISSUE TITLE
Generate after selection, not after cursor position

### ISSUE THREAD

**Issue by mrektor** [nhaouari/obsidian-textgenerator-plugin#112]
Hi!

I wanted to bring up a UX issue that I've been experiencing. Whenever I use the text generator and select the context from the end to the beginning, the output from the LLM is placed where the cursor is located, which is at the beginning of the text. 

It would be really helpful if there was an option to specify that the generated text be placed after the last part of the selected context, rather than the current position of the cursor in the note. This would greatly improve the usability of the feature.

I believe that this could be an excellent default behavior, but if you feel it's not appropriate, I would appreciate having the option to do so.

Thank you for your time and consideration.

**Comment by nhaouari** [comment]
Hi!

Thank you for bringing this issue to our attention. We appreciate your feedback and have addressed this bug in our latest release, version 0.2.16. Now, the generated text will be placed after the last part of the selected context by default.

We hope that this improvement enhances your experience with our text generator feature. Thank you again for your support and please don't hesitate to reach out if you have any further suggestions or feedback.

**Comment by mrektor** [comment]
Thank you for putting the effort! I really appreciate this project. I don't have the programming skills to contribute but I'm happy to provide suggestions if they are appreciated :) :)
