### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by Tarek-g** [nhaouari/obsidian-textgenerator-plugin#113]
I use macOS and encountered this error:

Error: Text Generator Plugin: An error has
occurred. Please check the console by
pressing CTRL+SHIFT+| or turn on display
errors in the editor within the settings for
more information.

Please find attached a screenshot of the error as well as a screenshot of the error message within the console.
<img width="1054" alt="Screenshot 2023-03-07 at 16 27 37" src="https://user-images.githubusercontent.com/13463837/223477777-a91091dc-ec94-4140-8059-b8c42dd0eeab.png">

**Comment by nhaouari** [comment]
Hello,
Please check the following issues

https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/9 https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/14 https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/28 https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/39 #90
