### ISSUE TITLE
Generation Hyperparameters in PromptInfo

### ISSUE THREAD

**Issue by mrektor** [nhaouari/obsidian-textgenerator-plugin#114]
Hi,

I don't know if this feature is already available (if it is, I wasn't able to find it), but it would be nice to include in the PromptInfo the possibility of setting the various hyperparameters to be sent to the OpenAi API

For example there are some prompts for which a low temperature is useful, others where a high is better.

Since the parameters name can evolve though time, it would be I think a nice design to have something like (example for a grammar fix prompt):

```
---
PromptInfo:
 promptId: fix grammar
 name: fix grammar
 description: fix the grammar of the text
 required_values: 
 author: 
 tags: 
generation_parameters: {
'temperature' = 0.1
}
 version: 0.0.1
---
This grammar converter is a program checks the LaTeX text for incorrect grammar, spelling, and punctuation, and then corrects it accordingly. The grammar converter also has a built-in dictionary to help locate and correct any unfamiliar words. 

INPUT: 
{{selection}}
OUTPUT:
```

So in general have a dict of parameters that override default generation parameters. One might also need to change other parameters by the way...

**Comment by nhaouari** [comment]
Check the following link http://text-gen.com/frontmatter-configuration

**Comment by mrektor** [comment]
Oh I see, but I can't find any example of a simple prompt that include also for example a change in temperature... I see only examples for Dalle and Bloom

**Comment by mrektor** [comment]
For example, does it need to be before prompt info, after prompt info, at the end, in between the `---` or as a new ```---section ---```?

**Comment by nhaouari** [comment]
This is an example.

**Comment by nhaouari** [comment]
To create a new template, follow these instructions:
1. Copy and paste the provided text into a new note.
2. Once completed, run the "TextGenerator: create a new template" command from the plugin settings (which should be enable it from the settings of the plugin).
3. To see the plugin as a command, reload it from the settings.
4. The template can now be easily accessed via ctrl+p or by assigning a hotkey in the Obsidian settings or via the different template commands .

```md
---
PromptInfo:
 promptId: fixGrammar
 name: fix grammar
 description: fix the grammar of the text
 required_values: 
 author: 
 tags:
 version: 0.0.1
 commands:
 - generate
bodyParams:
 temperature: 0.1
---
This grammar converter is a program checks the LaTeX text for incorrect grammar, spelling, and punctuation, and then corrects it accordingly. The grammar converter also has a built-in dictionary to help locate and correct any unfamiliar words. 

INPUT: 
{{selection}}
OUTPUT:

```
