### ISSUE TITLE
gpt-turbo-0301 model used when gpt-turbo-3.5 is selected

### ISSUE THREAD

**Issue by aarons** [nhaouari/obsidian-textgenerator-plugin#115]
Hi @nhaouari ,

This may be a misunderstanding on my part, but when I have `gpt-turbo-3.5` selected in the model list, the API calls `gpt-turbo-0301`. My preference would be to use the `turbo-3.5 model` instead, but I can't get it to stick. 

Here's a screenshot of the configuration selection and the request results coming back from openai:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/54643/223793103-41214930-2ff4-4792-8417-c2789b172e5b.png">

I did restart Obsidian, reloaded the plugin after changing the settings, and I'm using the latest version of TG (0.2.16). 

When I switched the model to text-davinci-003 that did update the model called in the request.

On a possibly related note, other models appear to fail when selected. To me, this is less important, although there are some models trained for editing code that would be nice to have access to. Let me know if this should be a separate issue, and I will write that up. I tried text-ada-001, code-davinci-edit-001, and a few others.

**Comment by nhaouari** [comment]
Thank you for bringing this to my attention. However, I have tried to reproduce the same error but was not able to encounter it. Have you tried updating the plugin? If not, please update the plugin and check if the issue still persists.

Let me know if there is anything else I can assist you with.

**Comment by aarons** [comment]
Hmm, weird. I was using 0.2.16, just updated to 0.2.17 and see the same issue.

I'm happy to try anything if it would be helpful to diagnose. I see this same behavior on both Windows and OSX. 

Below is a short recording, I make the call with a few text models and show the responses. Here is the order in the video: 

1. [option selected] -> [response model]
2. `gpt-3.5-turbo` -> `gpt-3.5-turbo-0301`
3. `davinci-003` -> `davinci-003`
4. `davinci-002` -> `davinci-002` 
5. `gpt-3.5-turbo` -> `gpt-3.5-turbo-0301` (at 33 second mark)
6. `gpt-3.5-turbo-0301` -> `gpt-3.5-turbo-0301`
7. `gpt-3.5-turbo` -> `gpt-3.5-turbo-0301`

https://user-images.githubusercontent.com/54643/224444170-55c5ecbb-2d1b-483c-be4e-21a22599d628.mp4

As a follow up test I also disabled all other plugins, but still saw the same issue.

**Comment by nhaouari** [comment]
The console displays the response content of the OpenAI request, which is not handled by the plugin. To view the actual request generated by the plugin, execute this command in the console: `localStorage.debug="textgenerator:*"`. 
Subsequently, search for `prepareReqParameters`. You will see that the selected model is used.
![image](https://user-images.githubusercontent.com/9850722/224834205-49065c31-1188-4239-8b6b-670b5e9e367e.png)

**Comment by aarons** [comment]
@nhaouari Thanks for closing this, and sorry for my late response. Thank you so much for getting back to me and explaining how to validate this.

I couldn't quite get the validation to work locally, but I think that's just user error / context on my part. No worries, and I really appreciate all the work you've been doing.

Cheers!
