### ISSUE TITLE
Status 429 error

### ISSUE THREAD

**Issue by Smitty010** [nhaouari/obsidian-textgenerator-plugin#117]
I just loaded text generator on.  When I try to run it, I get an error:
![image](https://user-images.githubusercontent.com/3760075/223829918-018be007-4bef-4918-8b37-9398a2e90e05.png)

I know what 429 means, but I've only run it a couple of times.  Does this mean that the server is busy with other people's requests?

I'm running Obsidian 1.1.16 and Text Generator 0.2.16 (the latest I think)
![image](https://user-images.githubusercontent.com/3760075/223833702-77a62d58-4b05-4a27-898e-23fa54b427b5.png)

btw - "Paramters" is missing an "e"

**Comment by nhaouari** [comment]
Check the following link: [http://text-gen.com/common-errors-in-openai-api-code-and-their-possible-causes](http://text-gen.com/common-errors-in-openai-api-code-and-their-possible-causes)

**Comment by Smitty010** [comment]
I figured this out before I saw your link.  But the link is correct.  You can get a 429 error if your $18 credit has expired and you have not set up a payment method.  That was my problem
