### ISSUE TITLE
Security Suggestion: storing API Key not in clear text has it is in data.json

### ISSUE THREAD

**Issue by JOduMonT** [nhaouari/obsidian-textgenerator-plugin#119]
Your plugin is simply wonderful and very useful to daily

While; it would be remarkable to not have the API key in clear text stored in the data.json
Would you be able to fix that, please?
https://forum.obsidian.md/t/store-secrets-like-api-key-outside-of-data-json/56035

**Comment by nhaouari** [comment]
Hey, 
Thanks for your nice words about our Text Generator plugin! 
It's great to hear that you find it helpful.

I totally get where you're coming from with your worry about the API key being stored in clear text in the data.json file. I'll definitely take a look at this and see if there's a way we can improve the security of the API key. 

If you have any other ideas or concerns, please don't hesitate to let us know!

**Comment by Dmusulas** [comment]
Hey, I believe this could be helpful https://www.electronjs.org/docs/latest/api/safe-storage, however the main drawback is this cannot be used for mobile. And because many people sync their obsidian vaults to access them from whenever I think enforcing this would be a mistake but adding as an option might be good.

**Comment by haouarihk** [comment]
i think we already added this feature in the v0.4.0+
it will try to encrypt keys, and if it cant, then it wont. that should keep the mobile compatibility

**Comment by haouarihk** [comment]
what do you think the default should be,
encryption or no encryption.

or should it look if it had mobile access before, if that then it will default to no encryption, otherwise do encryption?. what do you think

> Hey, I believe this could be helpful https://www.electronjs.org/docs/latest/api/safe-storage, however the main drawback is this cannot be used for mobile. And because many people sync their obsidian vaults to access them from whenever I think enforcing this would be a mistake but adding as an option might be good.
