### ISSUE TITLE
Request failed, status 401

### ISSUE THREAD

**Issue by NAL100** [nhaouari/obsidian-textgenerator-plugin#121]
Getting this error when trying to run the plugin. Any solutions?

> [!failure]- Failure 
>   Error: Request failed, status 401
>

**Comment by nhaouari** [comment]
Please check the following link : https://text-gen.com/common-errors-in-openai-api-code-and-their-possible-causes

**Comment by nhaouari** [comment]
I would like to suggest that you check the most recent version of the plugin, which is v0.3.1, as it features improved error messages that are more expressive. This update could enhance the overall performance and user experience of the plugin, and may provide helpful insights in the event of any issues that arise.
