### ISSUE TITLE
Hello! how to continue the query from the previous context?

### ISSUE THREAD

**Issue by medibb** [nhaouari/obsidian-textgenerator-plugin#122]
hello! 
This plug-in is so useful!
thank you for all these efforts!

My question is..
How to continue the query in the previous context?

Thank you!

**Comment by nhaouari** [comment]
Hello!
Thank you for your kind words about the plug-in. To continue the query in the previous context, you can simply generate the text in an empty new line which takes the full note as context.

If you're looking for more information on how to generate text that is considered within context, I would recommend checking out this link: https://text-gen.com/considered-context. It provides some great details and tips on how to generate text that is relevant context. 

I hope that helps! Let me know if you have any other questions.
