### ISSUE TITLE
Failed to install plugin "Text Generator"

### ISSUE THREAD

**Issue by ayoubamine** [nhaouari/obsidian-textgenerator-plugin#126]
Hello, I'm experiencing an issue with plugin installation. Please refer to the images below for more details. Thank you.

<img width="979" alt="1" src="https://user-images.githubusercontent.com/30782991/224488455-1ca5182e-40a5-4c90-95ad-3d4347b4e480.png">

<img width="663" alt="2" src="https://user-images.githubusercontent.com/30782991/224488466-e0b7675d-d20f-4b5d-88ec-d9d713a5a2dc.png">

**Comment by nhaouari** [comment]
Please check for updates and install the version 0.2.20. 
![image](https://user-images.githubusercontent.com/9850722/224494108-da1cdfbc-3c9d-4ff3-b7af-55ed87c06b99.png)
![image](https://user-images.githubusercontent.com/9850722/224494110-1b4ec8ac-f30e-48f7-af8a-63481bbeffc1.png)
