### ISSUE TITLE
Is there any plan to support open ai service in Azure?

### ISSUE THREAD

**Issue by amat27** [nhaouari/obsidian-textgenerator-plugin#130]
It will require the ability to replace base uri / leverage SDK to compose the uri from azure resource name

**Comment by nhaouari** [comment]
Unfortunately, I don't have access azure. You can change anything using the frontmatter [http://text-gen.com/frontmatter-configuration](http://text-gen.com/frontmatter-configuration).

**Comment by amat27** [comment]
Thanks.
