### ISSUE TITLE
[Feature Requests] Support for LaTex formatting

### ISSUE THREAD

**Issue by liuqi6777** [nhaouari/obsidian-textgenerator-plugin#133]
Hi!

As for my experience with this plugin, I discovered that the generated mathematical formulas were not being correctly rendered (as they were simply displayed as regular text instead of being embedded within "$" symbols as specified in markdown). As far as I know, the text returned by openai's model does have a "$" symbol, but I am unsure of how this particular plugin processes the text.

While I appreciate all of the plugin's functionalities, it would be even more useful to me personally if it could support LaTeX formatting. I would greatly appreciate it if you could take this feature into consideration for future implementations.

**Comment by nhaouari** [comment]
Hi! 
It does work, you need to specify this in the prompt. For example, `use KaTeX for math equations `

**Comment by liuqi6777** [comment]
Yes, it does work! Thank you for your reply.
