### ISSUE TITLE
GPT-4 model not working

### ISSUE THREAD

**Issue by xguntis** [nhaouari/obsidian-textgenerator-plugin#135]
I got access to GPT-4 api. After updating models i can select it from the list. However, when generating text I the the error
![image](https://user-images.githubusercontent.com/1523886/226161672-b0b7e89d-9dc4-4cbd-96cb-b61fc60471ac.png)

**Comment by nhaouari** [comment]
It is only accessible through a [waitlist](https://openai.com/waitlist/gpt-4-api).

**Comment by xguntis** [comment]
I already got the access to GPT-4 api. I got the following email

<html>
<body>


You're invited to use the OpenAI GPT-4 API!
--
You can now access GPT-4 models with 8K context via the existing OpenAI API.
Get started | Get started | Get started
Get started | Get started
Get started
As an early customer we'd love to hear about your experience. Feel free to share feedback on our community forum or reach out directly to our team.
Best,The OpenAI team


</body>
</html>You're invited to use the OpenAI GPT-4 API!
You can now access GPT-4 models with 8K context via the existing OpenAI API.

[Get started](https://mandrillapp.com/track/click/31165340/platform.openai.com?p=eyJzIjoiVjZYa2JfUHlCMm01b2paRWZNZ25qc2oxLTlzIiwidiI6MSwicCI6IntcInVcIjozMTE2NTM0MCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3BsYXRmb3JtLm9wZW5haS5jb21cXFwvZG9jc1xcXC9tb2RlbHNcXFwvZ3B0LTRcIixcImlkXCI6XCJlMWNlODQwYjI4ZjE0NjA1YTM1NWYzOGZhZDcwNTczY1wiLFwidXJsX2lkc1wiOltcIjljODBmZWRjNGY3ZDc1ZmQ4Y2FlNDEwNzczY2FjZjU5MDBlYjcyODlcIl19In0)
As an early customer we'd love to hear about your experience. Feel free to share feedback on our [community forum](https://mandrillapp.com/track/click/31165340/community.openai.com?p=eyJzIjoiaHFra081SmJKdFNlYXJ4YjZPRlVzcl84Z2FZIiwidiI6MSwicCI6IntcInVcIjozMTE2NTM0MCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2NvbW11bml0eS5vcGVuYWkuY29tXFxcL2NcXFwvZ2VuZXJhbC1hcGktZGlzY3Vzc2lvblxcXC83XCIsXCJpZFwiOlwiZTFjZTg0MGIyOGYxNDYwNWEzNTVmMzhmYWQ3MDU3M2NcIixcInVybF9pZHNcIjpbXCI5NTg5N2JjOGM3NzI2ZjFkMGRkYTQ0NTRhZmE4N2E4NTAwMDcxNWVkXCJdfSJ9) or reach out directly to our team.

Best,
The OpenAI team

**Comment by nhaouari** [comment]
Do you use the latest version of the plugin v0.2.21?

**Comment by xguntis** [comment]
i upgraded to v0.2.21 and now it works! Thanks! I am new to Obsidian. Didn't know I need to update plugins manually.
