### ISSUE TITLE
[feature request] Add a api_url options 

### ISSUE THREAD

**Issue by Jackiexiao** [nhaouari/obsidian-textgenerator-plugin#139]
sometimes we need a different api_url rather than `https://api.openai.com`, for example azure openai server or though a proxy server. could you add this option?

![image](https://user-images.githubusercontent.com/18050469/227776124-a3074bdf-0330-4257-b5b5-ad7140010503.png)

**Comment by nhaouari** [comment]
You can change the url using the frontmatter variables : [http://text-gen.com/frontmatter-configuration](http://text-gen.com/frontmatter-configuration)
