### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by brimwats** [nhaouari/obsidian-textgenerator-plugin#14]
Everytime I try to use the plugin lately I get error 429 (too many requests) but I'm not sending many requests at all

```
getLine was called on line 0
plugin:obsidian-textgenerator-plugin:200 {prompt: 'Explain the similarities and differences between quantitative and qualitative variables', max_tokens: 160, temperature: 0.7, frequency_penalty: 0.5}
plugin:obsidian-textgenerator-plugin:93 Error: Request failed, status 429
    at new t (app.js:1:699529)
    at nw (app.js:1:699721)
    at app.js:1:700398
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
```

**Comment by brimwats** [comment]
I seem to be getting error 400 now too. I tried using YAML and got a warning about invalid YAML: 

![image](https://user-images.githubusercontent.com/73113656/197900916-ecefd779-a9ef-4113-820d-f40444c1c969.png)


```


plugin:obsidian-textgenerator-plugin:200 {prompt: 'Explain the similarities and differences between quantitative and qualitative variables', max_tokens: 160, temperature: 0.7, frequency_penalty: 0.5}
plugin:obsidian-textgenerator-plugin:93 Error: Request failed, status 400
    at new t (app.js:1:699529)
    at nw (app.js:1:699721)
    at app.js:1:700398
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
```

**Comment by JohnPMills** [comment]
I am getting the same error.

**Comment by limex** [comment]
My guesses:
1) According to https://community.openai.com/t/how-to-fix-http-429-error/22790
there is a rate limit. number of requests / second,minute

**Comment by brimwats** [comment]
> My guesses:
> 
> 1. According to https://community.openai.com/t/how-to-fix-http-429-error/22790
>    there is a rate limit. number of requests / second,minute
>    or
> 2. You have no free usage (any more). Check https://beta.openai.com/account/usage. There should be something like a "$0.00 / $120.00". For the free trial period it is lower.
>    or
> 
> Maybe selecting text is needed before "Generate Text"? I noticed an empty payload in the request without selecting text upfront?

1. is that for every user of this specific plugin, or individual?

2. I have $100 in my OpenAI account 

3.  no difference on amount of text

**Comment by nhaouari** [comment]
see #28
