### ISSUE TITLE
Error: Request failed, status 404

### ISSUE THREAD

**Issue by piaoxi1517** [nhaouari/obsidian-textgenerator-plugin#140]
When I switch to the gpt4 model, the following error appears in the generated answer, but when I switch to gpt3.5, the correct result is output, why?

``` js
Error: Request failed, status 404

app.js:1 new t
app://obsidian.md/app.js:1:717762

app.js:1 Jw
app://obsidian.md/app.js:1:717954

app.js:1
app://obsidian.md/app.js:1:718631

app.js:1
app://obsidian.md/app.js:1:235836

app.js:1 Object.next
app://obsidian.md/app.js:1:235941

app.js:1 a
app://obsidian.md/app.js:1:234680
```

**Comment by dep** [comment]
Same issue for me. I have access to GPT-4, and I've also tried gpt-3.5-turbo, same error.

```
Error: Request failed, status 404
    at new t (app.js:1:717762)
    at Jw (app.js:1:717954)
    at app.js:1:718631
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
```

**Comment by dep** [comment]
Edit: Was able to update the plugin to latest and the problem seems to have resolved itself. Thanks!

**Comment by kgust** [comment]
How do you get whitelisted?

**Comment by nhaouari** [comment]
I would like to suggest that you check the most recent version of the plugin, which is v0.3.1, as it features improved error messages that are more expressive. This update could enhance the overall performance and user experience of the plugin, and may provide helpful insights in the event of any issues that arise.
