### ISSUE TITLE
Error: Request failed, status 429

### ISSUE THREAD

**Issue by koenbunders** [nhaouari/obsidian-textgenerator-plugin#143]
Error: Request failed, status 429

app.js:1 new e
app://obsidian.md/app.js:1:1626805

app.js:1 Wz
app://obsidian.md/app.js:1:1626997

app.js:1
app://obsidian.md/app.js:1:1627674

app.js:1
app://obsidian.md/app.js:1:235800

app.js:1 Object.next
app://obsidian.md/app.js:1:235905

app.js:1 a
app://obsidian.md/app.js:1:234644

**Comment by IssaAboudi** [comment]
I am also running into this issue. I expect that maybe the API might've changed on OpenAI's side and maybe that's contributing to the issue?

**Comment by tauren** [comment]
Just installed plugin for the first time and getting same problem.

**Comment by Larrtroffen** [comment]
I had no issues with it three hours ago, but now it is giving an error. Restarting the system and reinstalling the plugin have not worked.

**Comment by akonan** [comment]
Same here too. Tried different API keys and it doesn't work. It used to work with 3.5 but then I tried with 4 and started to get these errors. I switched back to 3.5 and still getting these.

**Comment by Bryce-Davidson** [comment]
Bump

**Comment by AlastairJarvis** [comment]
Also hitting this issue as tauren describes above. Worked with trial, upgraded to Pro, no longer works. Tried new API key, reinstalling plugin, reinstalling obsidian and plugin. Still hitting 429 error.

**Comment by peterdewinter** [comment]
On version 0.2.21 and the requests fail with status code 429.

```__async @ plugin:obsidian-textgenerator-plugin:50
editorCallback @ plugin:obsidian-textgenerator-plugin:47847
e.mobileOnly.$w.isMobile.e.checkCallback @ app.js:1
uR @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-textgenerator-plugin:47759 Error: Request failed, status 429
    at new t (app.js:1:717762)
    at Jw (app.js:1:717954)
    at app.js:1:718631
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
eval @ plugin:obsidian-textgenerator-plugin:47759
eval @ plugin:obsidian-textgenerator-plugin:66```

**Comment by nhaouari** [comment]
I would like to suggest that you check the most recent version of the plugin, which is v0.3.1, as it features improved error messages that are more expressive. This update could enhance the overall performance and user experience of the plugin, and may provide helpful insights in the event of any issues that arise.

**Comment by AlastairJarvis** [comment]
Thank you for the update. 

This is the new error text associated with this issue:

> Error: You exceeded your current quota, please check your plan and billing det ails.

Looks like an errant space is included in the word "details".

I will update as I learn more from OpenAI, but my best assessment is this is an issue at their end propagating purchase information from the stripe integrated app at chat.openai.com to the app at platform.openai.com

**Comment by AlastairJarvis** [comment]
One more piece of information that others may find useful and you may want to put in your FAQ. Paying for ChatGPT is not the same as setting up billing for OpenAI API, they are separate signups/billing. Many folks might be under the impression that having signed up for ChatGPT it should be possible to generate API keys from an expired trial account and have it work. It does not.
