### ISSUE TITLE
Ability to use a custom OpenAI URL

### ISSUE THREAD

**Issue by ytechie** [nhaouari/obsidian-textgenerator-plugin#147]
OpenAI is a service, but Azure also hosts an instance of the service (in preview). The only difference in code is that you have to specify the API base URL.

For example, in Python using the OpenAI package:
```python
openai.api_base = "https://my-instance-name.openai.azure.com/"
```

Can you expose this so that I can use OpenAI hosted in Azure?

**Comment by nhaouari** [comment]
check #139
