### ISSUE TITLE
text generator "fires" without being asked

### ISSUE THREAD

**Issue by Smitty010** [nhaouari/obsidian-textgenerator-plugin#149]
Since your last update (0.3.3), I've seen odd behavior.  I haven't used text generator today, but I saw evidence that several requests where made to openai (via some popup messages in Obsidian).  I have confirmed with my account that some requests where made.  This occurred a couple of times when I was inserting an image and once when I put my cursor in some templater code (text generator apparently passed the code in the templater block and got back a description of the code which it displayed in a popup message block). Text Generator is the only app on my computer that has the API key.  It seems pretty strange, but I can't think of anything else that has changed.

**Comment by nhaouari** [comment]
I think you have the auto-suggest option enabled.

**Comment by Smitty010** [comment]
It was on.  I've turned it off.  I'll assume that was the issue.  Funny, I didn't see it before.
