### ISSUE TITLE
[feature-request] allow for suggestions to automatically pop up while typing 

### ISSUE THREAD

**Issue by wardnath** [nhaouari/obsidian-textgenerator-plugin#15]
Is there a way to have this plugin give suggestions while typing rather than by manually pressing command? similar to Github copilot? 

see: ![copilot_typing](https://user-images.githubusercontent.com/4514195/198895246-6ae6df9c-1114-44cb-80fb-cb50b479abd2.gif)

example autocomplete in obsidian: https://github.com/tth05/obsidian-completr

**Comment by nhaouari** [comment]
check #100
