### ISSUE TITLE
Show Model from Template Not Working

### ISSUE THREAD

**Issue by dvansoye** [nhaouari/obsidian-textgenerator-plugin#151]
I'm having trouble with the Show Model from Template command.

I have a template with a required value. Here it is:

---
PromptInfo:
 promptId: formatBibleVerse
 name: 🗞️formatBibleVerse 
 description: formatBibleVerse
 required_values: verse
 author: Darren Van Soye
 tags: 
 version: 0.0.1
---
I want you to convert paragraph into a bible quote. This involves dropping text outside of the quotes, removing the quotation marks, adding a ”>” to the beginning and moving the reference to the end. Here's an example: 

Paragraph:
In 2 Corinthians 11: 3, our thoughtology professor Paul said, “I am afraid that just as Eve was deceived by the serpent’s cunning, your minds may somehow be led astray from your sincere and pure devotion to Christ.”

Bible verse:
>I am afraid that just as Eve was deceived by the serpent’s cunning, your minds may somehow be led astray from your sincere and pure devotion to Christ.—2 Corinthians 11:3

Do the same for the following paragraph:
{{verse}}

When I run this, I get the following error messages in the console.

POST https://api.openai.com/v1/chat/completions 400
eval @ plugin:obsidian-textgenerator-plugin:49572
eval @ plugin:obsidian-textgenerator-plugin:49556
eval @ plugin:obsidian-textgenerator-plugin:66
__async @ plugin:obsidian-textgenerator-plugin:50
request @ plugin:obsidian-textgenerator-plugin:49555
eval @ plugin:obsidian-textgenerator-plugin:49540
eval @ plugin:obsidian-textgenerator-plugin:66
__async @ plugin:obsidian-textgenerator-plugin:50
getGeneratedText @ plugin:obsidian-textgenerator-plugin:49536
eval @ plugin:obsidian-textgenerator-plugin:49353
eval @ plugin:obsidian-textgenerator-plugin:66
__async @ plugin:obsidian-textgenerator-plugin:50
generate @ plugin:obsidian-textgenerator-plugin:49333
eval @ plugin:obsidian-textgenerator-plugin:49636
fulfilled @ plugin:obsidian-textgenerator-plugin:53
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:65
eval @ plugin:obsidian-textgenerator-plugin:66
__async @ plugin:obsidian-textgenerator-plugin:50
eval @ plugin:obsidian-textgenerator-plugin:49628
handleSubmit @ plugin:obsidian-textgenerator-plugin:47625
callCallback2 @ plugin:obsidian-textgenerator-plugin:5620
invokeGuardedCallbackDev @ plugin:obsidian-textgenerator-plugin:5645
invokeGuardedCallback @ plugin:obsidian-textgenerator-plugin:5679
invokeGuardedCallbackAndCatchFirstError @ plugin:obsidian-textgenerator-plugin:5682
executeDispatch @ plugin:obsidian-textgenerator-plugin:8717
processDispatchQueueItemsInOrder @ plugin:obsidian-textgenerator-plugin:8737
processDispatchQueue @ plugin:obsidian-textgenerator-plugin:8746
dispatchEventsForPlugins @ plugin:obsidian-textgenerator-plugin:8754
eval @ plugin:obsidian-textgenerator-plugin:8878
batchedUpdates$1 @ plugin:obsidian-textgenerator-plugin:20350
batchedUpdates @ plugin:obsidian-textgenerator-plugin:5525
dispatchEventForPluginEventSystem @ plugin:obsidian-textgenerator-plugin:8877
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ plugin:obsidian-textgenerator-plugin:7208
dispatchEvent @ plugin:obsidian-textgenerator-plugin:7202
dispatchDiscreteEvent @ plugin:obsidian-textgenerator-plugin:7179
index.html:1 Uncaught (in promise) 
{message: "'content' is a required property - 'messages.0'", type: 'invalid_request_error', param: null, code: null}
code
: 
null
message
: 
"'content' is a required property - 'messages.0'"
param
: 
null
type
: 
"invalid_request_error"
[[Prototype]]
: 
Object
//end

The weird thing is that this works when I paste the prompt into a note and just Generate Text.

I want you to convert paragraph into a bible quote. This involves dropping text outside of the quotes, removing the quotation marks, adding a ”>” to the beginning and moving the reference to the end. Here's an example: 

Paragraph:
In 2 Corinthians 11: 3, our thoughtology professor Paul said, “I am afraid that just as Eve was deceived by the serpent’s cunning, your minds may somehow be led astray from your sincere and pure devotion to Christ.”

Bible verse:
>I am afraid that just as Eve was deceived by the serpent’s cunning, your minds may somehow be led astray from your sincere and pure devotion to Christ.—2 Corinthians 11:3

Do the same for the following paragraph:
In 2 Corinthians 11: 3, our thoughtology professor Paul said, “I am afraid that just as Eve was deceived by the serpent’s cunning, your minds may somehow be led astray from your sincere and pure devotion to Christ.”
>I am afraid that just as Eve was deceived by the serpent’s cunning, your minds may somehow be led astray from your sincere and pure devotion to Christ.—2 Corinthians 11:3
//end

The last two lines are the desired output.

So, there's something wrong with Show Model from Template.

This is a problem on Android and Windows.

I'm using 0.3.3 on both platforms.

Please let me know if there's any more information that you would want.

Thanks!

**Comment by nhaouari** [comment]
Thank you for bringing this issue to our attention. 
I'm happy to inform you that I has resolved the bug and implemented a fix. You can expect the fix to be included in the upcoming release. 
Thank you for your patience and continued support!

**Comment by dvansoye** [comment]
Great! Happy to hear that. Very fast turnaround. Excited to experiment further with templates.

**Comment by nhaouari** [comment]
@dvansoye I'm happy to inform you that the latest release is published.

**Comment by dvansoye** [comment]
Thanks so much for getting this out so fast!
