### ISSUE TITLE
[Feature request] speech to text using OpenAI Whisper

### ISSUE THREAD

**Issue by crypdick** [nhaouari/obsidian-textgenerator-plugin#154]
Obsidian lets you create voice notes. It would be nice if I could dictate a note and have it automatically transcribed using Whisper.

**Comment by nhaouari** [comment]
Obsidian has a core plugin called "Audio Recorder" that allows you to record your voice notes. Then, with the latest version 0.3.12 of Text Generator, you can use the "Text Extractor Tool" to extract the text from the recorded voice note and convert it into text.

**Comment by crypdick** [comment]
Thanks @nhaouari !
