### ISSUE TITLE
Auto-suggester doesn't work if when the model used is GPT-4

### ISSUE THREAD

**Issue by renatomen** [nhaouari/obsidian-textgenerator-plugin#155]
Hi @nhaouari . Thank you for the great work.

The auto-suggester doesn't work if GPT-4 is the chosen model.
(Works fine with GPT 3.5 Turbo)

**Obsidian version:** v1.2.5
**TG Version:** v0.3.14
Tested in multiple vaults. Including fresh installs.

# Steps to Reproduce
1 - Type a sentence and trigger the auto-suggestion feature (double space in my case)

# Expected Results
Auto-suggestions are offered in a dropdown

# Unexpected Results
The error message below is displayed.

[!failure]- Failure 
  TypeError: Cannot read properties of undefined (reading 'trim')
  
  - plugin:obsidian-textgenerator-plugin:58113 eval
    plugin:obsidian-textgenerator-plugin:58113:25
  
  - Array.map
  
  - plugin:obsidian-textgenerator-plugin:58112 AutoSuggest.eval
    plugin:obsidian-textgenerator-plugin:58112:28
  
  - Generator.next
  
  - plugin:obsidian-textgenerator-plugin:65 fulfilled
    plugin:obsidian-textgenerator-plugin:65:24

**Comment by nhaouari** [comment]
Thank you for bringing this issue to our attention. I am glad to inform you that we have fixed the auto-suggester issue with the GPT-4 model in the latest version of Text Generator, which is version 0.3.15. 

However, I would also like to advise you that using GPT-4 model for auto-suggest might incur higher costs as compared to GPT 3.5 Turbo. Therefore, we highly recommend reviewing the pricing details on the OpenAI website prior to using this model for auto-suggest.

We appreciate your support and feedback as we continue to improve Text Generator. Please let us know if you have any further questions or concerns.

**Comment by renatomen** [comment]
Awesome. You're incredible !
