### ISSUE TITLE
[Feature Request] Streaming text when generating

### ISSUE THREAD

**Issue by julianjuko** [nhaouari/obsidian-textgenerator-plugin#156]
Would it be possible to have an option to stream text word-by-word into my Obsidian note similar to how ChatGPT does when generating a response? I think this would improve the UX by creating a feeling of greater responsiveness. This would be especially nice when using GPT-4 with a high token limit.

**Comment by renatomen** [comment]
Hi @julianjuko ,

This feature is already available in the latest update. You can enable it in the plugin settings.
![image](https://user-images.githubusercontent.com/7007954/235269087-cc679147-8415-4bb0-b159-cf4178348757.png)

You can also make the "stop stream" command available in the obsidian command palette. Then associate a hotkey to it.
If you notice the text is not going in the direction you want, you can use the hotkey to stop the streaming.

![image](https://user-images.githubusercontent.com/7007954/235269176-f32b24e8-d028-49d1-82ab-b74bdb917692.png)

![image](https://user-images.githubusercontent.com/7007954/235269227-6b24c74d-37ca-49cc-b4fe-1b4c2d4e36cf.png)

**Comment by julianjuko** [comment]
Thanks a lot!
