### ISSUE TITLE
Request for support for external API key in a dotenv file

### ISSUE THREAD

**Issue by mofosyne** [nhaouari/obsidian-textgenerator-plugin#162]
I would like the plugin to read a .env file which may include something like

```
export OPENAI_API_KEY=
```

So i can easily exclude the file when syncing to a git repo.

Refer to https://levelup.gitconnected.com/obsidian-plugin-development-tutorial-how-to-use-environment-variables-d6f9258f3957 for implementation tip

Information about dotenv https://www.npmjs.com/package/dotenv

**Comment by haouarihk** [comment]
we don't have access to node access in obsidian.
we can't call for dotenv.

also it will be a weird configuration to handle all llm providers's apikeys

feel free to reopen it
