### ISSUE TITLE
Templates don't show in selection list

### ISSUE THREAD

**Issue by Hopsakee** [nhaouari/obsidian-textgenerator-plugin#164]
The templates don't show in the selection list.

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/28975522/00f3af82-37b1-4ef9-a6ef-e75c5b3c769a)

 Only after I created a new template, I am able to use the command: 

Templates: Generate & insert

I use a custom folder for the templates /Extra/textgenerator/prompts/

maybe that creates this issue?

**Comment by haouarihk** [comment]
remove the / at the end of your custom folder path
