### ISSUE TITLE
[Feature Request] Support private LLM models like PrivateGPT

### ISSUE THREAD

**Issue by quinn-p-mchugh** [nhaouari/obsidian-textgenerator-plugin#166]
Hi there,

The only thing preventing me from using this plugin is the privacy concerns.

If support for models like [PrivateGPT ](https://github.com/imartinez/privateGPT) were added, I would use it in a heartbeat.

**Comment by dxcore35** [comment]
Wau. That will be first ChatGPT plugin be privacy friendly!

**Comment by haouarihk** [comment]
not sure about PrivateGPT
but we do support opensource LLM providers like ollama,
you can also use gpt4ALL
or closed source but self hosted like LM Studio
