### ISSUE TITLE
[Feature Request] Add Azure OpenAI Support

### ISSUE THREAD

**Issue by DylanBCC** [nhaouari/obsidian-textgenerator-plugin#168]
Please add support for Azure OpenAI implementation of models

It uses different endpoint to the standard OpenAI one

API reference

https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference.

**Comment by nhaouari** [comment]
You can  change the endpoint from the setting of the plugin 
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/9850722/f49dcafb-7f92-4f06-a51f-d96f5ad8e105)

**Comment by DylanBCC** [comment]
Azure openai endpoint is structured differently to the openai endpoint. 

`https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/chat/completions?api-version={api-version}`

deployment-id is the model name

and also in the header

` -H "Content-Type: application/json" \
  -H "api-key: YOUR_API_KEY" \`

**Comment by nhaouari** [comment]
Thank you for providing the updated information on the structure of the Azure OpenAI endpoint. Based on the details you provided, here is an example frontmatter that you can try to make the command "generate text (with metadata)" work:

---
reqParams:
 url: "https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/chat/completions?api-version={api-version}"
 headers:
  Content-Type: "application/json"
  api-key: YOUR_API_KEY
---

Please replace {your-resource-name}, {deployment-id}, {api-version}, and YOUR_API_KEY with the appropriate values specific to your Azure OpenAI deployment. After setting up the frontmatter as mentioned above, you can attempt the "generate text (with metadata)" command and observe if it functions correctly.

**Comment by DylanBCC** [comment]
Thanks! for your fast response, I will give it a try soon
