### ISSUE TITLE
Feature request: Insert "generating..." text animation in editor while calling API

### ISSUE THREAD

**Issue by kepano** [nhaouari/obsidian-textgenerator-plugin#17]
Something that would really improve the UX of the plugin is inserting a loading animation where the generated text will appear, similar to some command line tools,

e.g. 

- `Generating.` `Generating..` `Generating...`
- or a spinning bar like `|` `/` `–` `\` `|` 

The benefit to the user is that you know that the plugin is processing, and where the text will be inserted

**Comment by nhaouari** [comment]
Implemented in version 0.1.0  #22  using text-spinners https://github.com/maxbeier/text-spinners. 
Thank you very much for your suggestion.
