### ISSUE TITLE
Expose API so it can be called from Templater or Dataview

### ISSUE THREAD

**Issue by dxcore35** [nhaouari/obsidian-textgenerator-plugin#173]
Please allow the usage of the plugin from javascript only. You will open whole new world for Templater user. And based on my research non of ChatGPT plugins in Obsidian plugin catalogue has access thru API.

https://forum.obsidian.md/t/templater-js-chatgpt/61755

Please! 🙏🏻

**Comment by haouarihk** [comment]
it is exposed 

https://docs.text-gen.com/_notes/2-+Options/Plugin+API
