### ISSUE TITLE
Image generation does not work if stream is true

### ISSUE THREAD

**Issue by mounta11n** [nhaouari/obsidian-textgenerator-plugin#174]
If the stream option is enabled in the configuration menu, and you want to generate an image by editing the frontmatter (set ` url: "https://api.openai.com/v1/images/generations"`), then the generation would not work. You have first to disable the stream option in the menu, then image generation will work again.

I think it the source code can be fixed easily, if we set a condition or something, but I am not that familiar with javascript unfortunately.

**Comment by haouarihk** [comment]
image generation works in version 0.5.25-beta (tested)

feel free to reopen this issue if its not
