### ISSUE TITLE
Unexpected `OPTIONS` call upon triggering `auto-suggest`

### ISSUE THREAD

**Issue by tslmy** [nhaouari/obsidian-textgenerator-plugin#176]
First of all, thanks so much for the work! It is the most promising GPT-powered text generation tool for Obsidian that I've seen.

# Behavior
Text Generator Plugin seems to send an `OPTIONS` request to the API endpoint upon triggering the `auto-suggest` feature.

# How discovered
Similar to the use case outlined in https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/166, I was trying to connect Text Generator Plugin to a local [LocalAI](https://github.com/go-skynet/LocalAI) server.

<img width="859" alt="image" src="https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/594058/6f0dc2dd-5d93-48ee-90a3-57240a4f48ae">

When I invoke `auto-suggest` with double whitespaces, I see a "failed to fetch" notification bubble at the top-right corner of Obsidian immediately.

With "display errors in the editor" enabled, I see the following message:

> [!failure]- Failure 
>   TypeError: Failed to fetch
>   
>   - plugin:obsidian-textgenerator-plugin:57307 eval
>     plugin:obsidian-textgenerator-plugin:57307:9
>   
>   - new Promise
>   
>   - plugin:obsidian-textgenerator-plugin:57291 TextGenerator.eval
>     plugin:obsidian-textgenerator-plugin:57291:14
>   
>   - Generator.next
>   
>   - plugin:obsidian-textgenerator-plugin:78 eval
>     plugin:obsidian-textgenerator-plugin:78:61
>   
>   - new Promise
>   
>   - plugin:obsidian-textgenerator-plugin:62 __async
>     plugin:obsidian-textgenerator-plugin:62:10
>   
>   - plugin:obsidian-textgenerator-plugin:57290 TextGenerator.request
>     plugin:obsidian-textgenerator-plugin:57290:12
>   
>   - plugin:obsidian-textgenerator-plugin:57275 TextGenerator.eval
>     plugin:obsidian-textgenerator-plugin:57275:86
>   
>   - Generator.next
>   
>  

At the same time, LocalAI server will log this message:

```
[127.0.0.1]:65200  405  -  OPTIONS  /v1/chat/completions
```

This means Text Generator Plugin is sending an `OPTIONS` request to `/v1/chat/completions`.

# Additional information

This `OPTIONS` request might be a browser security feature called "preflight request for CORS requests". I wonder if we could disable this.

GitHub Issue on the LocalAI side: https://github.com/go-skynet/LocalAI/issues/710#issuecomment-1617034758

**Comment by haouarihk** [comment]
i don't think its possible,
there isn't a option to opt out unless we use the obsidian request function (which has its own limitations).

browser does that when there are custom headers to CORS protected site
which are neccesary btw.
