### ISSUE TITLE
Considered context not working correctly

### ISSUE THREAD

**Issue by eddiecooro** [nhaouari/obsidian-textgenerator-plugin#177]
When I have a codeblock in my note that includes a frontmatter, The plugin mistakenly removes everything prior to that code block when trying to gather the considered context.

So for example:
````
---
name: A
---

# This is a MD file.

```
---
name: B
---
```
As you see, B was inside a codeblock in the page. 
````

This 👆 Will send "\`\`\`As you see, B was inside a codeblock in the page.\n" as context. Not the whole page.

I'd like to try to fix this issue myself if you want. Seems like a good first issue and I can familarize myself with the codebase in the process :pray:

**Comment by haouarihk** [comment]
should be fixed in the next release

**Comment by haouarihk** [comment]
can you test with the beta release

**Comment by haouarihk** [comment]
tested and its working on version 0.5.25-beta
i'm closing this issue
