### ISSUE TITLE
Error: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by Tarek-g** [nhaouari/obsidian-textgenerator-plugin#178]
After the [general availability](https://openai.com/blog/gpt-4-api-general-availability) of GPT-4 API, I encountered the following error:

> [!failure]- Failure 
>   Error: The model: `gpt-4` does not exist
>

**Comment by stuc2010** [comment]
I am also getting this error but it seems to be because my OpenAI account doesn't yet have access to GPT-4 despite it being GA. I would check if you have access to it in the OpenAI playground and confirm if you still get the error.

**Comment by haouarihk** [comment]
this is probably an old issue, i'm closing it

feel free to reopen it, if its not a tg issue
