### ISSUE TITLE
Conflict with Dictionary Plugin

### ISSUE THREAD

**Issue by Comprehensive-Jason** [nhaouari/obsidian-textgenerator-plugin#180]
The Text Generator plugin seems to conflict with the [obsidian-dictionary plugin](https://github.com/phibr0/obsidian-dictionary). When text-gen is enabled, the scroll bar in obsidian-dictionary disappears. 

https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/68677082/1a535e31-3101-4081-bc5e-72e246dbfd92

This might be a problem with other plugins as well.

**Comment by hcribeiro** [comment]
Similar issue, don't have dictionary plugin installed...

**Comment by haouarihk** [comment]
can you test it in version 0.5.27-beta
