### ISSUE TITLE
Support for locally hosted LLMs

### ISSUE THREAD

**Issue by Schallabajzr** [nhaouari/obsidian-textgenerator-plugin#182]
I was following a [blog post ](https://lmy.medium.com/how-to-get-notion-ai-like-autocomplete-with-llms-in-obsidian-offline-8ad98a8ecc81) and self hosting both:

- [alpaca.13b.ggmlv3](https://huggingface.co/westseer/alpaca.13b.ggmlv3)
- [ggml-gpt4all-j](https://gpt4all.io/models/ggml-gpt4all-j.bin)

the requests to these servers work via curl as per [this](https://github.com/go-skynet/LocalAI#example-use-gpt4all-j-model)
`
curl http://localhost:8080/v1/models
{"object":"list","data":[{"id":"gpt-3.5-turbo","object":"model"}]}%  
`

but when I try to communicate with it through the text generator plugin with the model rename to gpt-3.5-turbo to the self hosted instance (running inside docker at localhost:8080) I get the following error.
`
> [!failure]- Failure 
>   TypeError: Failed to fetch
>   
>   - plugin:obsidian-textgenerator-plugin:57307 eval
>     plugin:obsidian-textgenerator-plugin:57307:9
>   
>   - new Promise
>   
>   - plugin:obsidian-textgenerator-plugin:57291 TextGenerator.eval
>     plugin:obsidian-textgenerator-plugin:57291:14
>   
>   - Generator.next
>   
>   - plugin:obsidian-textgenerator-plugin:78 eval
>     plugin:obsidian-textgenerator-plugin:78:61
>   
>   - new Promise
>   
>   - plugin:obsidian-textgenerator-plugin:62 __async
>     plugin:obsidian-textgenerator-plugin:62:10
>   
>   - plugin:obsidian-textgenerator-plugin:57290 TextGenerator.request
>     plugin:obsidian-textgenerator-plugin:57290:12
>   
>   - plugin:obsidian-textgenerator-plugin:57275 TextGenerator.eval
>     plugin:obsidian-textgenerator-plugin:57275:86
>   
>   - Generator.next
>   
>  
`

**Comment by haouarihk** [comment]
The support for locally hosted llms are coming soon.
it is in the beta release,
it will be out soon

**Comment by dahifi** [comment]
+1 on this as well. LLStudio support with this will be awesome. 

Any related tasks on this @haouarihk, or are you doing all this in private?

**Comment by haouarihk** [comment]
> +1 on this as well. LMStudio support with this will be awesome.
> 
> Any related tasks on this @haouarihk, or are you doing all this in private?

i forgot to mention it there, LMStudio support is out,
if you want up to date tasks. you can join our discord community

**Comment by dahifi** [comment]
Relevant Discord link here: https://discord.com/channels/1083485983879741572/1159894948636799126
