### ISSUE TITLE
Ability to replace current text selection

### ISSUE THREAD

**Issue by andreicozma1** [nhaouari/obsidian-textgenerator-plugin#186]
I'm using templates for defining prompts for re-writing and re-styling text content.
Is there a feature to automatically replace the selected content with the generated text?

Currently, the generated text always gets inserted below the current selection, and I'm looking for a way to automatically replace the selection rather than inserting below.

**Comment by haouarihk** [comment]
make a template with mode: replace 
read the docs

**Comment by vishnuprksh** [comment]
read the docs, and still have no idea. Can someone help with this? As far as I know the template only helps to manipulate the prompt content, but how can we use it to delete the content from file itself?

**Comment by mapa17** [comment]
For those that actually are interested in an answer.
One can set a template to `replace` mode that will replace a selection with the generated output.
See https://docs.text-gen.com/_notes/3-+Templates/subpages/Template+Metadata
