### ISSUE TITLE
Feature Request for Auto Language Detection

### ISSUE THREAD

**Issue by miztizm** [nhaouari/obsidian-textgenerator-plugin#192]
Hello 
Firstly, thank you for developing this incredibly useful plugin. It's made my workflow in Obsidian much smoother.

I have a feature request that could further enhance the user experience: Would it be possible to implement auto-detection of the language used in a note? The idea is to generate titles that are contextually relevant to the language of the note. For example, if the note is written in French, the generated title should also be in French.

I believe this would be a valuable addition to the plugin, especially for those who often work with notes in multiple languages.

Thank you for considering this feature request. I look forward to any updates.

**Comment by haouarihk** [comment]
it should be done in version 0.5.25-beta
