### ISSUE TITLE
Text Generator error message

### ISSUE THREAD

**Issue by tuebels** [nhaouari/obsidian-textgenerator-plugin#196]
Dear Community, I have recently encountered some issues while using the Text Generator with my extensive Obsidian vault. I used to summarize or query for information from specific documents in my vault using this format:
"Please make a summary:
[[Position Paper Draft]]
The document appears to be a draft for a position paper. However, without specific content provided, it's impossible to provide a summary. A position paper typically presents an arguable opinion about an issue, providing evidence and reasons to support such views."
It used to function very stably, but recently I have been receiving error messages like the one above. Do you have any recommendations or solutions on how to resolve this issue? Thank you so much!

**Comment by haouarihk** [comment]
this is not an issue with text-generator
if you need help with prompting feel free to join our discord community and ask there.

i will close this, if you think i missed something feel free to reopen this issue
