### ISSUE TITLE
Text Generator used to work but now it's doesn't generate and no error msg

### ISSUE THREAD

**Issue by cahmitti123** [nhaouari/obsidian-textgenerator-plugin#197]
Hello, 
The Text genration button doesn't seem to do anything, u tryed to reload the pluging and changed the api token but nothing seems to work, and it doesn't even give me any error msg.

**Comment by medibb** [comment]
yeah, i encountered same issue after upgrade to chatGPT plus..doesn't even give me any error msg.

**Comment by haouarihk** [comment]
> yeah, I encountered the same issue after upgrading to chatGPT plus..doesn't even give me any error msg.
> 
> after re-install, i can use the text generator with GPT3.5-turbo.., but GPT-4 is not working even though i have upgraded to chatGPT plus plan.

its not the same as chatGPT plus plan, 
you need to go to the dashboard and add your payment information there,

**Comment by haouarihk** [comment]
i assume this issue is abandoned or already fixed.

feel free to reopen this issue
