### ISSUE TITLE
Assign models per template

### ISSUE THREAD

**Issue by pwntester** [nhaouari/obsidian-textgenerator-plugin#198]
Thanks for the awesome plugin! Is there any way of assigning a model for each template? I would like to use gpt-4 as the default one but I use gpt-3.5-16k for templated prompts that require a longer context. Is that possible?

**Comment by haouarihk** [comment]
yes, you can simply set frontmatter model to whatever model you want to use.

**Comment by pwntester** [comment]
Thanks @haouarihk, Should I put it in `bodyParams` or `config`?

**Comment by haouarihk** [comment]
in case you're using a custom request, you can use bodyParams,
but if you're not,
use `model` variable in the `config`
