### ISSUE TITLE
Disable auto-suggestions at the beginning of the line

### ISSUE THREAD

**Issue by chrisgrieser** [nhaouari/obsidian-textgenerator-plugin#200]
As far as I can tell, text generator the preceding text in a line as context for the auto-suggestions. This results in somewhat useless suggestions when you are at the very beginning of a line. 

Most notably, when using `space` as a trigger character, the suggestions for typing a list `- ` or a task `- [ ] ` are completely useless:

<img src="https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/73286100/20063850-fa3d-4ed7-bf84-0179c5de2bd8" alt="Pasted image 2023-10-17 at 15 19 58" width=50%>
<img src="https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/73286100/1d141698-90b0-40ac-b47c-ee1beabe023d" alt="Pasted image 2023-10-17 at 15 18 20" width=50%>

I would suggest to either disable suggestions when at the beginning of a line (e.g., no suggestions when the line has 10 characters or fewer), or to expand the context to include previous lines when there isn't enough context.

**Comment by haouarihk** [comment]
Thank you for reporting this issue

We totally agree, and it will be fixed in the next release
