### ISSUE TITLE
Generated backticks (``) are not in place

### ISSUE THREAD

**Issue by xela1601** [nhaouari/obsidian-textgenerator-plugin#212]
Hello there,
When i wanted to generate some text with this plugin, it somehow set the backticks in an unusual way. The backticks are somehow gathering at the end of the cursor.
This only occurs when the "Streaming" config is enabled. See screenshot attached.
![CleanShot 2023-11-06 at 22 09 32@2x](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/35468278/61236e23-a6d3-4e7b-be81-1c87ab8aa17d)

**Comment by haouarihk** [comment]
this should be fixed in version 0.5.20-beta

**Comment by haouarihk** [comment]
i assume this is fixed (because of no response)

if you think its not, feel free to reopen this issue
