### ISSUE TITLE
CORS issue when trying to generate text

### ISSUE THREAD

**Issue by taurr** [nhaouari/obsidian-textgenerator-plugin#213]
Using the OpenAI API, textgenerator has now resolved to fail in all text generations. The log says it all:

4 times this line:

Access to fetch at 'https://api.openai.com/chat/completions' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Then finally:

Error: Connection error.
    at OpenAI.makeRequest (plugin:obsidian-text…tor-plugin:14963:17)
    at async eval (plugin:obsidian-text…tor-plugin:21611:25)
    at async RetryOperation.eval [as _fn] (plugin:obsidian-text…ator-plugin:1271:19)

**Comment by haouarihk** [comment]
clear the basePath field under the llm provider settings in the plugin settings

**Comment by taurr** [comment]
yeah, that would be nice — except that with the newest update it couldn't even install this morning - I even tried deleting the plugin and its settings file, and it still can't even install!

**Comment by haouarihk** [comment]
what platform are you running it on

**Comment by haouarihk** [comment]
> Using the OpenAI API, textgenerator has now resolved to fail in all text generations. The log says it all:
> 
> 4 times this line:
> 
> Access to fetch at 'https://api.openai.com/chat/completions' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
> 
> Then finally:
> 
> Error: Connection error. at OpenAI.makeRequest (plugin:obsidian-text…tor-plugin:14963:17) at async eval (plugin:obsidian-text…tor-plugin:21611:25) at async RetryOperation.eval [as _fn] (plugin:obsidian-text…ator-plugin:1271:19)

try to do a reset
