### ISSUE TITLE
Did we lose the add title as metadata in beta version

### ISSUE THREAD

**Issue by OttoVanluchene** [nhaouari/obsidian-textgenerator-plugin#214]
Did we lose the add title as metadata in beta version?
This was very useful since most of my AI prompts are to get more information about the note title.
I don't want to duplicate the title in my frontmatter

**Comment by nhaouari** [comment]
In the latest version, you have greater customization options for crafting instructions. To utilize these, first enable them in the settings. Once activated, you can use a variety of variables to tailor your instructions more precisely to your needs.
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/9850722/506937d1-591b-4b5b-b079-ed9dbeb5cfe5)

**Comment by OttoVanluchene** [comment]
Ah we didn't loose it, it got better :) - thanks!
