### ISSUE TITLE
bug: "SyntaxError: Unexpected token '<', "<<<<<<< HE"... is not valid JSON"

### ISSUE THREAD

**Issue by chrisgrieser** [nhaouari/obsidian-textgenerator-plugin#223]
I recently started getting this error on Obsidian startup:

![Pasted image 2023-12-02 at 11 59 36@2x](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/73286100/88dc873f-e3f3-43b3-ba5f-c4710af98a35)

error in the console:
```
plugin:obsidian-textgenerator-plugin:180011 SyntaxError: Unexpected token '<', "<<<<<<< HE"... is not valid JSON
    at JSON.parse (<anonymous>)
    at PackageManager.load (plugin:obsidian-textgenerator-plugin:176841:33)
    at async TextGeneratorPlugin.onload (plugin:obsidian-textgenerator-plugin:179856:7)
```

The plugin itself appears to be unaffected though.

**Comment by haouarihk** [comment]
this should be fixed in version 0.5.21-beta
can you check?

> I recently started getting this error on Obsidian startup:
> 
> ![Pasted image 2023-12-02 at 11 59 36@2x](https://private-user-images.githubusercontent.com/73286100/287443280-88dc873f-e3f3-43b3-ba5f-c4710af98a35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTA1NzgsIm5iZiI6MTcwMjQ1MDI3OCwicGF0aCI6Ii83MzI4NjEwMC8yODc0NDMyODAtODhkYzg3M2YtZTNmMy00M2IzLWJhNWYtYzQ3MTBhZjk4YTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA2NTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDc2ZDYwMTkwMzQxZWY3MmM4NTBlOTY5N2RkNmJlYmViNjdiMTk3NGVmODBlZmFkN2EzOGI0N2Y1MmU1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vtaAHVl4dSFfjZSJ9OtONGS9Z8zZ9aaMG59bHFyntSY)
> 
> error in the console:
> 
> ```
> plugin:obsidian-textgenerator-plugin:180011 SyntaxError: Unexpected token '<', "<<<<<<< HE"... is not valid JSON
>     at JSON.parse (<anonymous>)
>     at PackageManager.load (plugin:obsidian-textgenerator-plugin:176841:33)
>     at async TextGeneratorPlugin.onload (plugin:obsidian-textgenerator-plugin:179856:7)
> ```
> 
> The plugin itself appears to be unaffected though.

**Comment by chrisgrieser** [comment]
yep, can confirm that the notification is now gone. Thank you!

**Comment by Vyeche** [comment]
I'm getting the same error. All outside plugins disabled.

```
app.js:1 SyntaxError: Unexpected token '<', "<<<<<<< HE"... is not valid JSON
    at JSON.parse (<anonymous>)
    at e.<anonymous> (app.js:1:2044615)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367)
```
