### ISSUE TITLE
Feature Request: Prefix override in template metadata

### ISSUE THREAD

**Issue by ironfroggy** [nhaouari/obsidian-textgenerator-plugin#224]
It would be useful to be able to disable or override the prefix string for specific templates. Is that something that could be added to the metadata allowed for configuring templates?

**Comment by haouarihk** [comment]
this is not a feature its a bug,
the prefix shouldn't be added when the output template is present
use the output template to form the shape however you like

this should get fixed in the next release, thanks for reporting it
