### ISSUE TITLE
CORS error when trying to use Mistral's API

### ISSUE THREAD

**Issue by skerit** [nhaouari/obsidian-textgenerator-plugin#226]
I'm trying to use Mistral's OpenAI compatible API, but I keep getting a CORS error:

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/755212/c1b81ed3-0537-4496-9215-300011c0bd62)

And `PreflightMissingAllowOriginHeader` etc.

Can something be done about this?
Like setting `no-cors`?

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/755212/b3e31ccc-3bbf-4f1e-946e-3bc58a021585)

**Comment by haouarihk** [comment]
We've contacted mistral support, we are waiting for a fix from their end.

**Comment by haouarihk** [comment]
this should be fixed in version 0.5.25-beta
