### ISSUE TITLE
`cmd+Q` should not be used as hotkey on mac

### ISSUE THREAD

**Issue by chrisgrieser** [nhaouari/obsidian-textgenerator-plugin#23]
With the new version, `cmd+Q` seems to be used as default hotkey. This should be avoided, since `cmd+Q` is the default macOS keybinding for quitting an app. (equivalent to `alt+f4` on windows)

<img width="1007" alt="Pasted image 2022-11-21 14 27 00" src="https://user-images.githubusercontent.com/73286100/203067071-0f09943b-816e-4189-99b5-e16a2628dd7b.png">

**Comment by nhaouari** [comment]
Thank you for bringing this to my attention! I will avoid using the cmd+Q hotkey in future versions. 

Do you have any suggestions for alternative hotkeys that we could use?

**Comment by chrisgrieser** [comment]
Not sure. Afaik, most bindings which only use `cmd` have some macOS function. If you avoid those, you should be good?

**Comment by nhaouari** [comment]
Update: Removing Default Hotkeys to Improve User Experience
I'm releasing an update (0.1.19) that removes the new default hotkeys that were introduced in version 0.1.x. These hotkeys caused conflicts with the system hotkeys used by Mac users. The following default hotkeys have been removed:

Alt + (1,2,3,4)
Ctrl/Alt+Q
Ctrl/Alt+Shift+Q
I apologize for any inconvenience this may have caused and I hope this update will improve your user experience.

Thank you for your continued support and feedback.

Sincerely,
Noureddine
