### ISSUE TITLE
CORS error when running Ollama

### ISSUE THREAD

**Issue by DoLife** [nhaouari/obsidian-textgenerator-plugin#230]
Access to fetch at 'http://127.0.0.1:11434/api/generate' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I`m running Ollama from a enviroment.conf file in the following way:
Environment="OLLAMA_ORIGINS=http://127.0.0.1:11434,app://obsidian.md:* ollama serve"

I have also tried:
OLLAMA_ORIGINS=* OLLAMA_HOST=127.0.0.1:11434 ollama serve

But the same results.

How can I bypass this CORS error?

**Comment by haouarihk** [comment]
https://discord.com/channels/1083485983879741572/1173386686751834162
