### ISSUE TITLE
is it possible to read an internal md file and extracte?

### ISSUE THREAD

**Issue by zacherywu0831** [nhaouari/obsidian-textgenerator-plugin#232]
Hi,
Thanks for the great work. Do help me a lot.
I am wondering how to make it read the internal links and give feedback, like:
```
Please read [[tempfile]] and give me the abstract.
```

Thanks for the advice.

**Comment by haouarihk** [comment]
https://docs.text-gen.com/_notes/3-+Templates/subpages/Handlebar+Templates#%60read%60
