### ISSUE TITLE
some images don't register as extractable

### ISSUE THREAD

**Issue by twilwa** [nhaouari/obsidian-textgenerator-plugin#233]
Hi,
I'm not sure if this a new/known issue, but i didn't see anything in the docs about it -- text extractor tool seems to no longer function with locally-linked images, only external ones. Is this a bug, an update i missed, something with my local config? Feel like it didn't used to be the case.

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/111034762/26312728-fc7e-4394-bb35-7c88ab7da58a)
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/111034762/41d8b4f4-f439-4da6-9d42-525007e02a80)

**Comment by haouarihk** [comment]
we will test it, 
sounds like a bug

**Comment by haouarihk** [comment]
found the issue, it will be fixed in the next release

**Comment by haouarihk** [comment]
should be fixed in version 0.5.28-beta
feel free to reopen the issue if its not working
