### ISSUE TITLE
extract text from ogg audio file (Text extractor tool)

### ISSUE THREAD

**Issue by krl91** [nhaouari/obsidian-textgenerator-plugin#234]
OGG format is supported by openai whisper but when I try to extract text from the audio file with the textgenerator plug-in, the OGG files are missing.

Why do we need ogg format (can bring more ideas...):

OpenAI Whisper is limited to processing audio files up to 25 MB, and although it supports many formats including OGG, Obsidian can only record audio in one file format, WebM, which isn't optimized enough. For instance, an hour of audio amounts to about 40 MB in the WebM format. However, if we compress it into an OGG format, using a command like "ffmpeg -i audio.webm -vn -map_metadata -1 -ac 1 -c:a libopus -b:a 12k -application voip audio.ogg" , the file size significantly reduces, going down to about 10% of its original size in my case.

**Comment by haouarihk** [comment]
this should be added in version 0.5.28-beta
