### ISSUE TITLE
When "Streaming" and "Output generated text to blockquote", redundant text is generated.

### ISSUE THREAD

**Issue by c-bun** [nhaouari/obsidian-textgenerator-plugin#235]
Screenshot attached. This only happens when both are turned on in the settings. Obsidian 1.5.3.
<img width="741" alt="Screenshot 2024-01-05 at 6 13 32 PM" src="https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/19352767/c9db5e96-9460-4139-bb92-e03c1fdfe959">

**Comment by haouarihk** [comment]
this should be fixed in version 0.5.28-beta
feel free to open if the issue comes back
