### ISSUE TITLE
set custom instructions dynamically

### ISSUE THREAD

**Issue by smallstepman** [nhaouari/obsidian-textgenerator-plugin#236]
custom instructions can drastically change quality of the output based on specific requirements. 

it would be nice to be able to set them dynamically via some option available from command palette, or even better, to be able to store the custom instruction in frontmatter or some other place directly inside the note

**Comment by haouarihk** [comment]
we are looking into it,
thanks for sharing the idea

**Comment by nhaouari** [comment]
It is possible to use the handlebar logic in the custom instructions, you have access to all the variables in the frontmatter. See  [https://handlebarsjs.com/guide/builtin-helpers.html#if ](https://handlebarsjs.com/guide/builtin-helpers.html#if )

**Comment by haouarihk** [comment]
you can set the custom instruction field in the settings to something like
```handlebars
{{yaml.instruction}}
```
and then go to your frontmatter and add variable
```
instruction: "you custom instruction here"
```
