### ISSUE TITLE
Use Goose AI instead of OpenAI

### ISSUE THREAD

**Issue by adeluccar** [nhaouari/obsidian-textgenerator-plugin#24]
Is it possible to choose an AI provider like Goose AI instead of OpenAI?

They advertise the same feature set (and API command parity) with OpenAI but the service is significantly more cost-effective which would increase the use of the Text Generator plug-in.

https://goose.ai/docs

**Comment by willmartinss** [comment]
I'd also like the possibility of changing service providers.

That being said, _I've tested the most of the advanced models offered by Goose AI, including the newest "GPT-NeoX 20B" and I found it to be nowhere close in capabilities to GPT-3. I didn't test it thoroughtly, though. 

Having options other than OpenAI woud be terrific.
Thank you!

**Comment by nhaouari** [comment]
It is possible to configure other services through the front matter. Check the following link https://text-gen.com/frontmatter-configuration. 

 If you have any issues, please let me know.
