### ISSUE TITLE
Text Generator altering `textarea` inputs in other plugins

### ISSUE THREAD

**Issue by brianpetro** [nhaouari/obsidian-textgenerator-plugin#241]
The issue is that the altered `textarea` is unreadable. 

Example can be found here https://github.com/brianpetro/obsidian-smart-connections/issues/412

We were able to solve the issue in the above example by disabling Text Generator.

This also seems related to #231 

Thanks for your help in solving this!

🌴

**Comment by haouarihk** [comment]
we will work on it

**Comment by haouarihk** [comment]
continue discution in #231
