### ISSUE TITLE
[enhancement] Turn off slash commands

### ISSUE THREAD

**Issue by Smitty010** [nhaouari/obsidian-textgenerator-plugin#245]
It seems like you should be able to turn off slash commands invoking textgenerator templates and probably change the character that invokes the templates.  I would like to use the old slash commands as implemented in Obsidian.

**Comment by haouarihk** [comment]
you can turn off slash commands,
its called modal-suggest and you can turn it off in the settings.

and about changing the character invoking it, we don't have plans for it yet

**Comment by Smitty010** [comment]
I think being able to turn off the slash commands is probably sufficient.  I did look through the options and "modal-suggest" didn't suggest what it was going to do.  It might be better to give it name like "slash suggestions".  Cheers
