### ISSUE TITLE
Issues with setting Ollama LLM Provider

### ISSUE THREAD

**Issue by Huarch** [nhaouari/obsidian-textgenerator-plugin#246]
**Env:**

OS: MacOS
Others: Local Ollama

**TextGen Setting:**

LLM Provider: Ollama
Model: phi
Base Path: http://localhost:11434

**What happened:**

I can not generate anything but get error of "Failed to Fetch", CORS should be right after enter `OLLAMA_ORIGINS=* OLLAMA_HOST=127.0.0.1:11435 ollama serve` into terminal. 

More than this, I test Ollama Plugin and it works well. And Llama Coder Plugin in VSC, works well too.

**Error Info:**
```
TypeError: Failed to fetch

plugin:obsidian-textgenerator-plugin:29943 createOllamaStream
plugin:obsidian-textgenerator-plugin:29943:26

createOllamaStream.next

plugin:obsidian-textgenerator-plugin:29983 createOllamaGenerateStream
plugin:obsidian-textgenerator-plugin:29983:10

createOllamaGenerateStream.next

plugin:obsidian-textgenerator-plugin:30289 Ollama._streamResponseChunks
plugin:obsidian-textgenerator-plugin:30289:26

plugin:obsidian-textgenerator-plugin:30317 async Ollama._call
plugin:obsidian-textgenerator-plugin:30317:26

async Promise.all

plugin:obsidian-textgenerator-plugin:15840 async Ollama._generate
plugin:obsidian-textgenerator-plugin:15840:29

plugin:obsidian-textgenerator-plugin:15718 async Ollama._generateUncached
plugin:obsidian-textgenerator-plugin:15718:20

plugin:obsidian-textgenerator-plugin:15813 async Ollama.call
plugin:obsidian-textgenerator-plugin:15813:33
```

**Comment by haouarihk** [comment]
origin should be set to this:
OLLAMA_ORIGINS=http://192.168.1.1:*,app://obsidian.md:* ollama serve

heres the [discord thread](https://discord.com/channels/1083485983879741572/1173386686751834162)

**Comment by GeoZhanglw** [comment]
The same problem bothered me. 
It said: TG error, Ollama call failed with status code503: Service Unavailable
I tried just as you said, but it didn't work.
