### ISSUE TITLE
Is it possible to add Openrouter?

### ISSUE THREAD

**Issue by firsteyev** [nhaouari/obsidian-textgenerator-plugin#248]
I always use models from Openrouter's api key. Is it possible to add Openrouter option?

**Comment by haouarihk** [comment]
> I always use models from Openrouter's api key. Is it possible to add Openrouter option?

- use `OpenAI Chat` llm provider
- set the base path to `https://openrouter.ai/api/v1`
- search for `Experimental features` enable it, then you should be able to set custom value to the model field
