### ISSUE TITLE
Error since update

### ISSUE THREAD

**Issue by platothefish** [nhaouari/obsidian-textgenerator-plugin#25]
Hi, 
Since the last update I keep getting an error. It is going through to OpenAI as I am being charged but the text isn't displaying on the obsidian page. It was working okay before I updated the plugin. 

<img width="372" alt="Screenshot 2022-11-22 at 21 38 10" src="https://user-images.githubusercontent.com/44426282/203426677-ae421d59-d44e-46ad-988e-b01530ebb090.png">

<img width="354" alt="Screenshot 2022-11-22 at 21 42 52" src="https://user-images.githubusercontent.com/44426282/203427099-37aaeff8-396d-4448-84f0-396323423ab2.png">

**Comment by nhaouari** [comment]
Hi,

I'm sorry to hear that you're having trouble with the plugin. Could you please send me the error message you're seeing so I can take a look? You can do this by opening the Developer Tools (Ctrl+Shift+I on Windows, Cmd+Opt+I on Mac) and clicking on the "Console" tab. Then, try running your command again and see if any error messages appear.

Thanks,

**Comment by platothefish** [comment]
Sure here you go:
plugin:obsidian-textgenerator-plugin:31334 RangeError: Selection points outside of document
    at fn (app.js:1:280706)
    at new e (app.js:1:288772)
    at Function.e.create (app.js:1:288932)
    at Zn (app.js:1:291312)
    at e.update (app.js:1:293570)
    at e.dispatch (app.js:1:434438)
    at t.setSelection (app.js:1:1369354)
    at t.e.setCursor (app.js:1:1126136)
    at TextGeneratorPlugin.endProcessing (plugin:obsidian-textgenerator-plugin:32038:14)
    at TextGenerator.eval (plugin:obsidian-textgenerator-plugin:31331:21)
![Screenshot 2022-11-23 at 12 59 13](https://user-images.githubusercontent.com/44426282/203552877-9ab73123-99c5-4956-a12f-420887b65dfa.png)

**Comment by nhaouari** [comment]
Hi,

Thanks for sending over the error message. Can you please also send me the document content and list of commands and actions you've done? That would help me reproduce the error.

In the meantime, you can try using an older version of the plugin [(0.0.10)](https://github.com/nhaouari/obsidian-textgenerator-plugin/releases/tag/0.0.10), you can do this by downgrading it manually `vault/plugins/obsidian-textgenerator-plugin`.
Thanks,

**Comment by platothefish** [comment]
I just tried it on a new clean note and exactly the same, I also tried it with the sidebar and just the same
![Screenshot 2022-11-23 at 15 26 17](https://user-images.githubusercontent.com/44426282/203584639-71a8bee9-16a9-4404-9315-2e8270fb1735.png)

**Comment by nhaouari** [comment]
Hi,

The plugin has been updated to version 0.1.2 and should be working now. If you have any further issues, please let me know.

Thank you,
