### ISSUE TITLE
Azure OpenAI Api not working - presence_penalty's default should be 0 (instead of null)

### ISSUE THREAD

**Issue by haejoonchoi** [nhaouari/obsidian-textgenerator-plugin#250]
For my generation call to Azure OpenAI, I am getting below error, and I can see that in the payload, presence_penalty is set to null, which is a default value set in `src\LLMProviders\langchain\azureOpenAIChat.tsx`. From what I see, the number should be 0 or it'd be even nicer if we have a slider control in the config page of the Text Generator plugin then use that value. 

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/20471931/36e4663a-1229-4db3-a372-12214db31744)

**Comment by haouarihk** [comment]
This should get fixed in the next release (0.6.14) 

Thanks for reporting this issue

**Comment by haejoonchoi** [comment]
Thank you for working on this issue!
