### ISSUE TITLE
Azure OpenAI Api issue - when baseUrl is present

### ISSUE THREAD

**Issue by haejoonchoi** [nhaouari/obsidian-textgenerator-plugin#251]
I found some issues with the Azure OpenAI Api when the baseUrl is present, please check below (I'd be happy to make bug fix PR myself, if allowed)

## When BaseUrl is present
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/20471931/2f0813d1-a550-40ac-b3e9-c171aedb1a04)
- `openai/deployments/` part is missing in the Request URL
- The clean-up of slash should be implemented after `.com` (you can see two forward-slashes)

## When BaseUrl is not present
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/20471931/bc941093-44f8-465a-9067-b700837d1200)

**Comment by haouarihk** [comment]
for the azure openAI its not baseURL
its endpoint it should be in the format `https://[instanceName].openai.azure.com/openai/deployments`

the instanceName input will be useless if you set the endpoint.

and about the `/` at the end of the url we will roll out a fix that would remove it if its present.

if you ask why is the basepath in this format,
that's how the langchain team decided it will be, i'm afraid if we make our own wrapper on top of it, it might break some people's usecases.

Thanks for the report
