### ISSUE TITLE
Mistral provider doesn't set `api_key` correctly to accept change model

### ISSUE THREAD

**Issue by ncoquelet** [nhaouari/obsidian-textgenerator-plugin#253]
# Reproduce steps
1. install Text generator
2. Go settings, choose `MistralAI Chat` provider and enter the API key
3. Choose a model and click on the reload button
=> **"Please provide a valid api key"** error

# Investigations
- `LLMProviders/utils.tsx` check on `global.plugin.settings.api_key.length`, https://github.com/nhaouari/obsidian-textgenerator-plugin/blob/74557f29e1b6c60e13e6e8841d7be0ccd5fc9a0c/src/LLMProviders/utils.tsx#L36
- `LangchainMistralAIChatProvider` doesn't set `global.plugin.settings.api_key.length`, https://github.com/nhaouari/obsidian-textgenerator-plugin/blob/74557f29e1b6c60e13e6e8841d7be0ccd5fc9a0c/src/LLMProviders/langchain/mistralaiChat.tsx#L95

# WorkAround
- select `OpenAI Chat` first
- enter the API key
- Switch on `MistralAI Chat`

Thank a lots for your excellent plugins

**Comment by haouarihk** [comment]
or we can just let it check for `config.api_key` instead.
Thanks alot,
this investigation was very helpful

it will be fixed in the next version

**Comment by ncoquelet** [comment]
I confirm the fix in lastet beta version, thanks
