### ISSUE TITLE
call model-selector from command palette

### ISSUE THREAD

**Issue by winne617** [nhaouari/obsidian-textgenerator-plugin#254]
in version 0.3 there was a command for a window to open to choose the model from. 
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/131215156/54d3fee4-fa6c-41ae-ab44-ee1bb34afb2b)

it's not there any more. can we have this back please? i use that quite regularly and call it via a keyboard hotkey i defined for that.

thanks a lot;)

**Comment by ncoquelet** [comment]
I think that a work around is configuring "OpenAI Chat 1" and "OpenAI Chat 2" extra provider.
Or use the `model` property inside the frontmatter of your prompt template https://docs.text-gen.com/_notes/3-+Templates/subpages/Template+Metadata#%60model%60

**Comment by haouarihk** [comment]
we will be adding profiles soon, and you can name them whatever you like.
choosing a model only works with openai's llm provider, and we want to have all our utils work with all of the llm providers.

there is a posibility for it coming back, but for now profiles is our focus right now

**Comment by winne617** [comment]
ah, ok. thx

**Comment by haouarihk** [comment]
profiles are now out, you can use them in 
version 0.7.3
