### ISSUE TITLE
What input for BasePath Llama2?

### ISSUE THREAD

**Issue by Hottorun** [nhaouari/obsidian-textgenerator-plugin#260]
Hey, 
Could someone help set up llama2 or tell me what to write for the base path? 
I am running Llama locally, will it work or do i need aws sever or something?
Thanks

**Comment by haouarihk** [comment]
no, you don't need an external server, that's the whole point of local hosting.
that's what localhost means.
anyway
Follow this guide
https://discord.com/channels/1083485983879741572/1202326921858523246
it should help you out
