### ISSUE TITLE
Unable to enable streaming when LLM provider is set to ollama

### ISSUE THREAD

**Issue by dossjj** [nhaouari/obsidian-textgenerator-plugin#262]
I am using ollama as my LLM provider but I am unable to enable Streaming in the settings. Nothing happens when I click the toggle button. Streaming with Ollama works with other applications and other Obsidian plugins.

I am running on macos and my ollama instance is running on a different PC on my home network. Generation works, just not streaming.

Is streaming not supported with the ollama provider?

**Comment by haouarihk** [comment]
we will roll out a fix in the next release thanks for reporting it

**Comment by haouarihk** [comment]
can you test with [0.7.2-beta](https://github.com/nhaouari/obsidian-textgenerator-plugin/releases/tag/0.7.2-beta) beta release

**Comment by haouarihk** [comment]
it should be fixed in version 0.7.3, if not
feel free to reopen this issue

**Comment by dossjj** [comment]
Streaming is now working great after updating. Thanks you.
