### ISSUE TITLE
Request for Clarification on Code Formatting Best Practices

### ISSUE THREAD

**Issue by ncoquelet** [nhaouari/obsidian-textgenerator-plugin#264]
Hey there,

I'm reaching out to discuss the code formatting practices within this project. I've noticed we have a `.editorconfig` file, yet it seems like its rules aren't fully applied—perhaps because 4-space tabs aren't as popular anymore :smile: 

Personally, I use VSCode with Prettier, which automatically formats and tidies up imports on save. I could adjust my setup to disable these features for this project, but it got me thinking: shouldn't it be the project's responsibility to enforce formatting standards, rather than leaving it up to individual contributors?

What's your take on this? Should we look into more uniform enforcement of these rules, possibly integrating tools like Prettier to automate the process?

Looking forward to your thoughts.

Best,

**Comment by haouarihk** [comment]
that is true,
we also use format on save feature,

- We need a github action that would check the formattting.
- We also need to setup tailwind order formatter.

if someone can help out with these, that will be great.

for the first one, i think its just a prettier check command, and use the on pull request event.

the second one is just a plugin added, and then (in a second pull request) fixing all classes

**Comment by ncoquelet** [comment]
Thank you for your response
I just pushed a PR #268  proposing a config for formatting ts/json/md/... files + a Github action
I haven't touched the Tailwind config yet, it's not really my specialty
Let me know what you think?
