### ISSUE TITLE
When using a custom LLM provider, model defaults to gpt-3.5-turbo until model list is updated

### ISSUE THREAD

**Issue by danielfaust** [nhaouari/obsidian-textgenerator-plugin#265]
I added Groq as a LLM Provider as shown in the Tweet https://twitter.com/TextGenPlugin/status/1763526171868729488

To select `mixtral-8x7b-32768`, I pressed the reload button in the Model row and selected it from the bottom of the list.

When I later reopen the settings, the model doesn't show `mixtral-8x7b-32768` but `gpt-3.5-turbo`. When I press the reload button in the Model row, then `mixtral-8x7b-32768` is shown as the selected model again.

It appears that the plugin isn't caching the model list, so that the entry isn't available when the settings are shown, resulting in an erroneous display.

**Comment by haouarihk** [comment]
This should be fixed in version 0.6.7 i belive.

now it will show you the selected model even tho its not in the list.
