### ISSUE TITLE
Mistral API doesn't work

### ISSUE THREAD

**Issue by SleepingSmel** [nhaouari/obsidian-textgenerator-plugin#275]
Hi! Well, for some weeks I've been using Mistral API with success, however, now a pop-up with an error shows up.

The synergy between Mistral and Obsidian it's amazing, please help me fix this. Thanks!

![Screenshot 2024-03-17 112141](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/139800632/f4f31c95-7e84-4510-9d37-d01a11558747)
![Screenshot 2024-03-17 112408](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/139800632/baf4f353-4334-474f-891b-fab791fb30e4)

**Comment by ncoquelet** [comment]
Hi,
Do you try to update the plugin ? 
last version is 0.7.11

**Comment by SleepingSmel** [comment]
Yes! It's fixed, thanks :)

**Comment by ivankrdenas** [comment]
Hi, same error I'm in 0.7.41 version.
