### ISSUE TITLE
Always update after restarting of obsidian

### ISSUE THREAD

**Issue by merlinuwe** [nhaouari/obsidian-textgenerator-plugin#276]
The plugin tries to update itself, but it does not get the latest release.

(Seems to be an issue with some plugins since the last obsidian update.)

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/4138869/3aa00be6-795b-4ed4-80a3-233270689be3)

**Comment by Smitty010** [comment]
+1

**Comment by josephworks** [comment]
It appears that the version in the manifest from the 0.7.11 update still says 0.7.8:
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/18745823/c4ed5227-55e2-4d88-89c7-396bf6743bc4)

My fix was to edit the manifest version to 0.7.11 and the issue was fixed.

**Comment by merlinuwe** [comment]
After this I could install the update, but the text in the manifest is the same as before.

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/4138869/a56aa399-a66c-4e5c-bf76-9568060b6c81)

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/4138869/b98ed1ae-79df-4364-ad48-e2b3f473b09c)

And it doesn't update again.

**Comment by haouarihk** [comment]
updated the manifest.json file in the release,
this should fix it.

lmk to close this issue

**Comment by josephworks** [comment]
Yep, LGTM. Feel free to close the issue.

Thank you!
