### ISSUE TITLE
plugin error v1.2

### ISSUE THREAD

**Issue by DavitCH** [nhaouari/obsidian-textgenerator-plugin#28]
Hello,
in v1.1 there was an error message when pressing Ctrl+J or executing the command from the sidebar.
Shortly after you released v1.2 to fix it but the error is still there :(
![image](https://user-images.githubusercontent.com/44007440/203881918-fed1d21c-aa1d-46bd-8a34-e80562098e5e.png)

**Comment by nhaouari** [comment]
Hello, thank you for letting me know. This might be because the document is empty.

**Comment by nhaouari** [comment]
The **429** error means that you are making too many requests to OpenAI and are being rate-limited.

**Comment by cyc115** [comment]
Running into the same error. The plugin makes 4 consecutive requests to OpenAI with every invocation. Only the first call succeeds and the rest fails with Http 429. Could you help investigate why there are dup requests? 
![image](https://user-images.githubusercontent.com/2107333/204119013-2f6314fd-88dd-45d5-8a6e-659ea93a1194.png)

**Comment by DavitCH** [comment]
Im just an idiot and used an API key from an account where i do not have a valid OpenAI subscribtion.
Used the API key from another account and its working fine now.
Sorry for causing inconveniences! :\
