### ISSUE TITLE
[YoutubeTranscript] 🚨 TypeError: Cannot read properties of undefined (reading 'transcriptBodyRenderer')

### ISSUE THREAD

**Issue by ckt1031** [nhaouari/obsidian-textgenerator-plugin#283]
Following to the docs, still get error.

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/65409152/41508f18-18cf-405c-ae93-363137c4c71e)

**Comment by ckt1031** [comment]
https://github.com/langchain-ai/langchainjs/issues/4994

**Comment by hardchor** [comment]
@ckt1031 should we keep this issue open until it's been fixed upstream?

**Comment by ckt1031** [comment]
> @ckt1031 should we keep this issue open until it's been fixed upstream?

I believe no, cuz it is fixed in main branch.
However, the stable release still lacks this change, so current solution is to use a cloudflare worker to handle the captions grabbing

**Comment by hardchor** [comment]
For future readers with the same issue (until this gets released in the next stable release):

You can quite easily install the latest pre-release from this repo using the BRAT plugin: https://github.com/TfTHacker/obsidian42-brat! Just add `https://github.com/nhaouari/obsidian-textgenerator-plugin` as a source, all the other settings should be fine as they are.
