### ISSUE TITLE
GPT-4o ist not accessible yet

### ISSUE THREAD

**Issue by Lucero-brilliante** [nhaouari/obsidian-textgenerator-plugin#289]
in the LLM-Settings I can´t choose the model GPT-4o as it is not included in the slection

**Comment by nhaouari** [comment]
## Method 01 
https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/9850722/ebaa02bf-ddcf-4ed6-b158-e9b036beac2a

## Method 02 

https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/9850722/d5e51d59-e3ca-4a8b-beb9-750a5c87c299

**Comment by Lucero-brilliante** [comment]
Thanks a lot for your support. Both solutions work fine!
