### ISSUE TITLE
TG Error: this.plugin.app.vault.getFolderByPath is not a function

### ISSUE THREAD

**Issue by MakiWinster** [nhaouari/obsidian-textgenerator-plugin#290]
I downloaded the Released interface `obsidian-textgenerator-plugin-0.7.11.zip`, unzipped it, dragged and dropped it into Obsidian and got the following prompt:  
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/84610999/7c87d242-99ac-4845-a9b2-3290f7db6718)  
  
After I set it up normally, I tried to call up the AI by pressing the setup shortcut, only to find that he didn't have a button to display the shortcut  
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/84610999/22ca0c92-5eee-46a5-98b5-19bdc8e92f24)  
  
How do I do it?

**Comment by haouarihk** [comment]
this is just an issue with updating obsidian version
