### ISSUE TITLE
x-stainless-os header being added in mom-Mistral api requests

### ISSUE THREAD

**Issue by jvsteiner** [nhaouari/obsidian-textgenerator-plugin#294]
I have a custom OpenAI compatible endpoint I am trying to use (at runpod in a serverless environment).    I created a customer endpoint, based on the OpenAPI pattern in the settings.  Unfortunately, I get the following error on the developer console:

>Access to fetch at 'https://api.runpod.ai/v2/{my_endpoint_id}/openai/v1/chat/completions' from origin 'app://obsidian.md' has been blocked by CORS policy: Request header field x-stainless-os is not allowed by Access-Control-Allow-Headers in preflight response.

I searched the repository for `x-stainless-os`  and the only place I see this header is in [src/LLMProviders/langchain/mistralaiChat.tsx](https://github.com/nhaouari/obsidian-textgenerator-plugin/blob/890bfbada7c5ccb9db9963e20b0690d2df729186/src/LLMProviders/langchain/mistralaiChat.tsx#L31)  which is the Mistral object.  Any idea why is would be getting added to a request made using the OpenAI pattern? the actual production OpenAI endpoints don't care about it, but the runpod endpoints do, and afaict, there is not any way to add custom headers at runpod.

**Comment by haouarihk** [comment]
its built into the openai library.
the only way to go around it, is by using the custom provider

**Comment by jvsteiner** [comment]
this is what I eventually did.
