### ISSUE TITLE
dependencies broken for fresh install

### ISSUE THREAD

**Issue by jvsteiner** [nhaouari/obsidian-textgenerator-plugin#295]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: obsidian-textgenerator-plugin@0.7.10-beta
npm ERR! Found: three@0.155.0
npm ERR! node_modules/three
npm ERR!   three@"^0.155.0" from the root project
npm ERR!   peer three@">=0.133" from @react-three/fiber@8.16.8
npm ERR!   node_modules/@react-three/fiber
npm ERR!     peerOptional @react-three/fiber@"*" from framer-motion@5.6.0
npm ERR!     node_modules/framer-motion
npm ERR!       framer-motion@"^5.6.0" from the root project
npm ERR!       1 more (@chakra-ui/menu)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional three@"^0.135.0" from framer-motion@5.6.0
npm ERR! node_modules/framer-motion
npm ERR!   framer-motion@"^5.6.0" from the root project
npm ERR!   peer framer-motion@">=4.0.0" from @chakra-ui/menu@2.2.1
npm ERR!   node_modules/@chakra-ui/menu
npm ERR!     peer @chakra-ui/menu@"^2.0.0" from chakra-react-select@4.8.0
npm ERR!     node_modules/chakra-react-select
npm ERR!       chakra-react-select@"^4.7.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/jamie/.npm/_logs/2024-06-14T12_42_12_355Z-eresolve-report.txt

**Comment by haouarihk** [comment]
removed three js package, its not even being used.

also use pnpm instead of npm.
