### ISSUE TITLE
TG5 - error code (no body)

### ISSUE THREAD

**Issue by splanker** [nhaouari/obsidian-textgenerator-plugin#299]
Text generation plugin has been working fine, now suddenly I'm getting the error: TG5 - error code (no body)

I'm using openrouter api
checked that openrouter api hasn't changed
tried new api key
updated text generation plugin
updated obsidian
restarted text generation plugin
restarted obsidian
windows 10 (if that matters)
BRAT extension previously (to disable annoying surprise changes to the UI)
turned BRAT off
restarted obsidian
tried again, still broken
did a google search
did a perplexity search
cried
sighed
now I'm here

Not sure what to do next.
Anyone else getting this error?

**Comment by AeonSunLVX** [comment]
Same. It works with Auto-Suggest and my default model. But templates throw the error.

**Comment by splanker** [comment]
It seems to have randomly fixed itself. I hope you have the same luck!
