### ISSUE TITLE
FR: The information about the number of max tokens in the status bar is optional

### ISSUE THREAD

**Issue by Liong1976** [nhaouari/obsidian-textgenerator-plugin#3]
First of all, I want to thank you for making this amazing plugin,

I wondered if you could make the information about the number of max tokens in the status bar optional so that it doesn't make my status bar full. Thanks

![image](https://user-images.githubusercontent.com/88898230/155911257-a9d52897-4d2a-4573-a575-5140fe0a24fe.png)

**Comment by nhaouari** [comment]
You're welcome, I will do that in the next Release.
