### ISSUE TITLE
Custom api  model case wrong

### ISSUE THREAD

**Issue by issakk** [nhaouari/obsidian-textgenerator-plugin#304]
when request,the model name will be low case,this may cause exception
e.g.  i put 'ERNIE' in model, when request,it turns to 'ernie'

**Comment by haouarihk** [comment]
what llm provider are you using.

langchain providers such as openai chat, anthropic chat.
they all use the langchain library which makes the model case insensitive

**Comment by issakk** [comment]
i am using baidu model named ERNIE-Speed-128K  through one-api  
it throws 'not found model ernie-speed-128k' when input low case

in my opinion,may be the plugin dont need to change the case?

thanks for reply,it is a great plugin

**Comment by haouarihk** [comment]
this will be fixed in the next release
