### ISSUE TITLE
Why it is not allowing more than 4096 tokens as max tokens for gpt-4o

### ISSUE THREAD

**Issue by munish259272** [nhaouari/obsidian-textgenerator-plugin#305]
![image](https://github.com/user-attachments/assets/a91b2990-3838-43e1-97d3-ff5181830a67)

Text generator settings :
![image](https://github.com/user-attachments/assets/6bcee32b-6ea1-4208-9846-16731cdad16b)

These are my defined limits on the openai website.
![image](https://github.com/user-attachments/assets/6943eb3f-43d8-434f-a40b-fa5277581997)

**Comment by haouarihk** [comment]
that's the output tokens.
its limited to 4096.
also if you check the error. its coming from openai.
its not issue in the plugin

**Comment by munish259272** [comment]
Thanks for the info, i got it now. I thought it included input as well.
This can be closed
![image](https://github.com/user-attachments/assets/4631d6cf-f3ee-447e-b6a7-54b023b424dd)
