### ISSUE TITLE
Custom model gives error with Auto-Suggest due to invalid user role

### ISSUE THREAD

**Issue by baroxyton** [nhaouari/obsidian-textgenerator-plugin#309]
Hello! I use groqs openAI compatible API with this plugin. It works, however when I try Auto-Suggest option, I get an error from the API:

    Error: 'messages.0' : discriminator property 'role' has invalid value

upon investigating, I found that the autocomplete option uses a `human` role and I believe the issue would be fixed if it was changed to `user` instead

Auto-Suggest request:
![grafik](https://github.com/user-attachments/assets/a9bd0c18-3d00-4b60-83d1-0049bffc4da9)

Generate text:
![grafik](https://github.com/user-attachments/assets/45936334-f1f9-41a9-b1e3-42c1a43d4146)

**Comment by haouarihk** [comment]
this will be fixed soon
