### ISSUE TITLE
Code display instead of loading dots

### ISSUE THREAD

**Issue by rshklarek** [nhaouari/obsidian-textgenerator-plugin#31]
<img width="1920" alt="Screen Shot 2022-11-28 at 08 47 11" src="https://user-images.githubusercontent.com/33123708/204223508-6ab8e02e-5c16-42d1-a872-3f3ae50acda9.png">
Hi,

first thank you for this incredible plugin. 

I've experienced some minor issues. One depicted here with the screenshots is that the loading dots display as codes instead of the animation. This only happens on macOS and not on the iOS version, at least for me.

Best
Raphael

**Comment by nhaouari** [comment]
Hi Raphael,

Thank you for letting me know about this issue. I am aware of the issue and am currently working on a fix #30 . Thank you for your patience!

Best,
