### ISSUE TITLE
Error: 401 / 404

### ISSUE THREAD

**Issue by johnafarmer** [nhaouari/obsidian-textgenerator-plugin#315]
I'm encountering Error: 401, and Error: Request failed, status 404, when attempting to generate text using the plugin. 

![Screenshot 2024-09-16 160828](https://github.com/user-attachments/assets/278c6fae-1d81-4f81-a9a8-ecfaefc405a3)

> [!failure]- Failure 
>   Error: 401 {"type":"error","error":{"type":"authentication_error","message":"C  ORS requests must set 'anthropic-dangerous-direct-browser-access' header"}}
>   
>   - plugin:obsidian-textgenerator-plugin:498 I.generate
>     plugin:obsidian-textgenerator-plugin:498:17725
>   
>   - plugin:obsidian-textgenerator-plugin:501 Jl.makeStatusError
>     plugin:obsidian-textgenerator-plugin:501:6747
>   
>   - plugin:obsidian-textgenerator-plugin:501 Jl.makeRequest
>     plugin:obsidian-textgenerator-plugin:501:7659
>   
>   - plugin:obsidian-textgenerator-plugin:15 async ki.eval [as _fn]
>     plugin:obsidian-textgenerator-plugin:15:63402
>   

---

> [!failure]- Failure 
>   Error: Request failed, status 404
>   
>   - app.js:1 new t
>     app://obsidian.md/app.js:1:2030716
>   
>   - app.js:1 vK
>     app://obsidian.md/app.js:1:2030908
>   
>   - app.js:1 
>     app://obsidian.md/app.js:1:2031587
>   
>   - app.js:1 
>     app://obsidian.md/app.js:1:237138
>   
>   - app.js:1 Object.next
>     app://obsidian.md/app.js:1:237243
>   
>   - app.js:1 a
>     app://obsidian.md/app.js:1:235961
>

**Comment by Olivmamman** [comment]
I get similar issue while using Claude Sonnet

```
TG Error: 401 {
"type":"error": {
"type":"authentication_error","message":
"CORS requests must set 'anthropic-dangerous-direct-browser-access' header"
}
}
```

**Comment by Dnarts** [comment]
same here 

plugin:terminal:110 Error: 401 {"type":"error","error":{"type":"authentication_error","message":"CORS requests must set 'anthropic-dangerous-direct-browser-access' header"}}
    at I.generate (plugin:obsidian-textgenerator-plugin:498:17725)
    at Jl.makeStatusError (plugin:obsidian-textgenerator-plugin:501:6747)
    at Jl.makeRequest (plugin:obsidian-textgenerator-plugin:501:7659)
    at async ki.eval [as _fn] (plugin:obsidian-textgenerator-plugin:15:63402)

**Comment by derSebastian** [comment]
Get the same problem with v 0.7.43

When adding the Anthropic API key and trying to refresh the models I get a quick 404 error notification.

**Comment by daxmonson** [comment]
Getting this as well: "CORS requests must set 'anthropic-dangerous-direct-browser-access' header"}}"

TG  V0.7.47
