### ISSUE TITLE
Failure to read files in Obsidian v1.7.2

### ISSUE THREAD

**Issue by Comprehensive-Jason** [nhaouari/obsidian-textgenerator-plugin#319]
[Obsidian 1.7.2](https://obsidian.md/changelog/2024-09-19-desktop-v1.7.2/) made some changes to how plugins are loaded. 

Now, when starting Obsidian, Text Generator 'attempts to get files' 30 times before erroring out. While doing so, Obsidian is stuck on the Loading Plugins screen.

![image](https://github.com/user-attachments/assets/6cd05cc9-5fcc-47f0-8e7f-717751c54baa)
![image](https://github.com/user-attachments/assets/88e7fc64-0e7e-4ed9-993b-859453750413)

**Comment by OttoVanluchene** [comment]
Takes 90sec to load Obsidian with text generator on 😮

**Comment by OttoVanluchene** [comment]
This is now fixed for me with the latest update 👍 thanks
