### ISSUE TITLE
No valid metadata (YAML front matter) found

### ISSUE THREAD

**Issue by rshklarek** [nhaouari/obsidian-textgenerator-plugin#32]
<img width="1920" alt="Screen Shot 2022-11-28 at 08 57 52" src="https://user-images.githubusercontent.com/33123708/204224191-b9f09a16-1ab1-4f06-b7df-8aad6ebe1156.png">
Hi me again,

this is the second error I've found. Maybe I've got a formatting error but I tried to cover all my bases before posting. This happens on macOS as well as on iOS.

Best
Raphael

**Comment by nhaouari** [comment]
Please check #6 #8

**Comment by Radifire** [comment]
![image](https://user-images.githubusercontent.com/64096772/204629042-ac07275c-7cce-44b0-b497-ecd031f2e05c.png)
I seem to be getting the same issue, despite both trying to paste the example as a plain text, as well as typing it out manually.

**Comment by nhaouari** [comment]
Could you please try opening the Developer Tools console (Ctrl+Shift+i) and seeing if there are any errors being displayed there and run this command `app.metadataCache.getCache(app.workspace.getActiveFile().path)` ? 

That might give us a clue as to what's going on.

**Comment by nhaouari** [comment]
Hi @rshklarek ,

Please check the last fix on version 0.1.4 and let me know if it's still not working for you.

Best,

**Comment by Radifire** [comment]
Sorry for the late response.

The plugin seems to be working as intended now for me. 

Thanks for the swift fix.

**Comment by pdworkman** [comment]
I have updated to version 0.1.4 but I am also getting the No valid metadata error.

**Comment by nhaouari** [comment]
> 

Could you please try opening the Developer Tools console (Ctrl+Shift+i) and seeing if there are any errors being displayed there and run this command app.metadataCache.getCache(app.workspace.getActiveFile().path) ?

That might give us a clue as to what's going on.

**Comment by pdworkman** [comment]
No errors on the console.

What response did you expect to see with that command? Do you need me to
expand any more of this out?

[image: image.png]

Pam

P.D. Workman

Award-winning and USA Today Bestselling Author
Find me at pdworkman.com
Hot new release!
*They Came for Him*
A gritty P.I. mystery series
<https://www.facebook.com/facebook.com/pdworkmanauthor>
<https://www.linkedin.com/linkedin.com/in/pdworkman>
<https://www.twitter.com/twitter.com/pdworkmanauthor>
------------------------------
Join my e-mail list <https://pdworkman.com/signup> to get a free ebook and
to be notified when my books are published.
------------------------------

**Comment by MavropaliasG** [comment]
I am facing the same issue. Below is my YAML (words replaced by XXX)

---
title: "XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX"
keywords: XXX XXX, XXX XXX, XXX XXX, XXX, XXX, XXX, XXX, XXX, XXX XXX, XXX, XXX, XXX, XXX, XXX XXX
---

**Comment by nhaouari** [comment]
> If you don't find frontmatter in the output after running `app.metadataCache.getCache(app.workspace.getActiveFile().path)`, the issue is not related with Text Generator Plugin.  I think you might have some ymal formating issues.
