### ISSUE TITLE
Failed To Install Plugin - Possible Conflict With SystemSculpt?

### ISSUE THREAD

**Issue by richardstevenhack** [nhaouari/obsidian-textgenerator-plugin#320]
Version 0.7.38 Installed. 
Update is available according to Obsidian Community Plugins Update button.
I update. 
Get message "Failed to install plugin." 
I remain on 0.7.38.
Reboot Obsidian, try again, same result.
Tried in Obsidian Sandbox vault - same result.

Obsidian version: 1.6.7
OS: openSUSE Tumbleweed Linux latest
Note: I have other AI plugins installed, including SystemSculpt which interestingly remained installed when I switched to the Obsidian Sandbox vault to test installing Text Generator. Possible conflict between those two.

**Comment by koldex** [comment]
I'm trying to update from 0.7.37 and I failed as well. Following debug log entry is generated:

app.js:1 Error: Request failed, status 404
    at new t (app.js:1:2057697)
    at SK (app.js:1:2057889)
    at app.js:1:2058568
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.installPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
Gb @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1

**Comment by marjomol** [comment]
I'm trying to install the plug-in for the first time and the same error appears.
(using Ubuntu)

**Comment by nidhoggr-nil** [comment]
I have the same issue. Tried uninstalling it and then installing it since it failed to update. Now it can't install.



Request failed, status 404

{
    "cache-control": "no-cache",
    "content-encoding": "gzip",
    "content-length": "41",
    "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    "content-type": "application/json; charset=utf-8",
    "date": "Fri, 20 Sep 2024 13:30:31 GMT",
    "referrer-policy": "no-referrer-when-downgrade",
    "server": "GitHub.com",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
    "x-content-type-options": "nosniff",
    "x-github-request-id": "B942:1718BC:2D55150:2E33086:66ED7926",
    "x-xss-protection": "0"
}

**Comment by merlinuwe** [comment]
Update does not work, new install does not work.

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.8.1
	Snippets enabled: 58
	Restricted mode: off

**Comment by Smitty010** [comment]
+1.  Note that I do NOT have systemsculpt installed
SYSTEM INFO:
	Obsidian version: v1.7.2
	Installer version: v1.6.5
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Primary v2.9.1
	Snippets enabled: 16
	Restricted mode: off
	Plugins installed: 105
	Plugins enabled: 65
		1: Tasks v7.10.0
		2: Templater v2.7.1
		3: Calendar v1.5.10
		4: Kanban v2.0.51
		5: Excalidraw v2.5.0
		6: Outliner v4.8.1
		7: Natural Language Dates v0.6.2
		8: QuickAdd v1.11.1
		9: Periodic Notes v0.0.17
		10: Homepage v4.0.4
		11: Minimal Theme Settings v8.1.1
		12: Note Refactor v1.8.2
		13: Spaced Repetition v1.12.6
		14: Style Settings v1.0.9
		15: Workspaces Plus v0.3.3
		16: Tag Wrangler v0.6.1
		17: Hotkeys++ v0.2.7
		18: Fullscreen mode plugin v0.1.2
		19: Projects v1.17.4
		20: Plugin Update Tracker v1.5.2
		21: Open vault in VSCode v1.2.3
		22: Grandfather v1.0.1
		23: No dupe leaves v0.0.12
		24: Callout Manager v1.1.0
		25: Quiet Outline v0.3.36
		26: Linter v1.26.0
		27: MySnippets v1.2.3
		28: Auto Link Title v1.5.4
		29: Status Bar Pomodoro Timer v0.1.14
		30: Advanced URI v1.44.1
		31: Update time on edit v2.4.0
		32: Metadata Menu v0.8.7
		33: Scroll to Top v2.1.4
		34: Supercharged Links v0.12.1
		35: Dataview v0.5.67
		36: Sort Frontmatter v1.0.24
		37: Charts v3.9.0
		38: Quick Switcher++ v4.5.0
		39: Editing Toolbar v2.4.16
		40: Settings Search v1.3.10
		41: Gemini Assistant v1.0.4
		42: Beautitab v1.6.1
		43: Omnisearch v1.24.1
		44: Meta Bind v1.1.3
		45: Text Extractor v0.5.2
		46: Advanced Canvas v3.1.0
		47: Canvas minimap v1.0.15
		48: File Cooker v1.9.0
		49: Commander v0.5.1
		50: Sortable v0.3.1
		51: Banners v1.3.3
		52: Copy as source v1.0.2
		53: Advanced Tables v0.22.0
		54: Footnote Shortcut v0.1.3
		55: Text Generator v0.7.38
		56: Admonition v10.3.2
		57: Highlightr v1.2.2
		58: Modal forms v1.51.0
		59: CardBoard v0.7.9
		60: File Explorer Note Count v1.2.2
		61: CSS Inlay Colors v1.1.0
		62: Block Link Plus v1.0.4
		63: Text Format v3.1.0
		64: Lazy Plugin Loader v1.0.18
		65: Recent Files v1.6.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by merlinuwe** [comment]
> Update does not work, new install does not work.
> 
> SYSTEM INFO: Obsidian version: v1.6.7 Installer version: v1.6.7 Operating system: Windows 10 Home 10.0.19045 Login status: not logged in Insider build toggle: off Live preview: off Base theme: dark Community theme: MagicUser v20.8.1 Snippets enabled: 58 Restricted mode: off

Ok, then I'll drop my pants too ... ;-)

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.8.1
	Snippets enabled: 58
	Restricted mode: off
	Plugins installed: 194
	Plugins enabled: 73
		1: Lazy Plugin Loader v1.0.18
		2: Custom Font Loader v1.5.5
		3: Natural Language Dates v0.6.2
		4: Navigate Cursor History v1.1.0
		5: Open File by Magic Date v0.1.2
		6: Remember cursor position v1.0.9
		7: Reset Font Size v1.0.2
		8: Set View Mode per Note v1.0.3
		9: Tab Switcher v1.4.0
		10: Beautitab v1.6.1
		11: Custom Classes v2.6.1
		12: Dataview v0.5.67
		13: Dictionary v2.22.0
		14: Editing Toolbar v2.4.16
		15: Enhancing Export v1.10.7
		16: Gallery v0.5.8
		17: Image in Editor v2.2.6
		18: Linter v1.26.0
		19: Omnisearch v1.24.1
		20: Quick Explorer v0.2.10
		21: Quick Switcher++ v4.5.0
		22: Status Bar Organizer v2.1.2
		23: Style Settings v1.0.9
		24: Supercharged Links v0.12.1
		25: Table Generator v1.4.1
		26: Tag Wrangler v0.6.1
		27: Tasks v7.10.0
		28: Templater v2.7.1
		29: Typing Transformer v0.4.0
		30: Webpage HTML Export v1.8.01
		31: Backlink Cache v1.8.1
		32: Commander v0.5.1
		33: Dashboard navigator v2.0.0
		34: Recent Files v1.5.0
		35: PDF++ v0.40.9
		36: Editor Syntax Highlight v0.1.3
		37: Enhanced Symbols Prettifier v1.4.0
		38: Excel to Markdown Table v0.4.0
		39: Tldraw v1.7.2
		40: Google Calendar v1.10.15
		41: Hover Editor v0.11.20
		42: Image Converter v1.1.7
		43: Note Toolbar v1.12.5
		44: Number Headings v1.16.0
		45: Query Control v0.6.0
		46: Virtual Linker / Glossary v1.5.0
		47: Print v0.3.6
		48: Paste image rename v1.6.1
		49: Plugins Annotations v1.7.2
		50: Refresh Preview v1.3.0
		51: Sortable v0.3.1
		52: Actions URI v1.6.4
		53: Advanced Tables v0.22.0
		54: Advanced URI v1.44.1
		55: Android nomedia v0.1.0
		56: Auto Hide Cursor v1.1.0
		57: Auto Link Title v1.5.4
		58: Better Export PDF v1.9.2
		59: Book Search v0.7.4
		60: Copy document as HTML v0.8.1
		61: Docxer v2.0.1
		62: Export Image plugin v2.3.13
		63: File Explorer Note Count v1.2.2
		64: Find orphaned files and broken links v1.10.1
		65: Local Backup v0.1.7
		66: markdown export v1.0.24
		67: Multi Properties v1.1.2
		68: Quiet Outline v0.3.36
		69: Sheet Plus v1.3.6
		70: Show Current File Path v0.5.2
		71: Show Whitespace v0.2.3
		72: Vault Changelog v0.1.0
		73: Vault Statistics v0.1.3

**Comment by haouarihk** [comment]
> Version 0.7.38 Installed. Update is available according to Obsidian Community Plugins Update button. I update. Get message "Failed to install plugin." I remain on 0.7.38. Reboot Obsidian, try again, same result. Tried in Obsidian Sandbox vault - same result.
> 
> Obsidian version: 1.6.7 OS: openSUSE Tumbleweed Linux latest Note: I have other AI plugins installed, including SystemSculpt which interestingly remained installed when I switched to the Obsidian Sandbox vault to test installing Text Generator. Possible conflict between those two.

i believe it was a mistake on my end, i updated manifest.json with the wrong verion number. last time.
but now it should work

**Comment by richardstevenhack** [comment]
I just reinstalled the latest version. It's installed properly now. Thanks for the quick response!

**Comment by Smitty010** [comment]
I successfully installed the latest version.  Looks like it is working again.
