### ISSUE TITLE
[Bug] Options - Changing "Prompts Templates Path" before downloading templates cause an empty "Insert Template" list

### ISSUE THREAD

**Issue by willmartinss** [nhaouari/obsidian-textgenerator-plugin#35]
It appears that there's a bug where the downloaded Prompt templates are not installed correctly if a different prompt template path is set in Options.

**Steps to reproduce:**

1. Install and enable plugin
2. Go to Options and change "Prompts Templates Path" to a different path (e.g., "openai/prompts")
3. Use Ctrl+P and open the "Template Package Manager"
4. Install any of the Prompt packages
5. Try to insert a Template using the "Insert Template" command

**Actual Result:**

- The "Insert Template" pop-up shows an empty list.

_The templates are installed to the default path: "textgenerator/prompts,  instead of the path set in the Options._

Please let me know if you need more details.

_Thank you for this wonderful plugin!_
William

**Comment by nhaouari** [comment]
Thank you William,

I've just released a new version of the plugin (0.1.5) that should fix the issue. Please let me know if it's still not working for you.

Best,

**Comment by willmartinss** [comment]
I was not able to recreate the issue on version 0.1.5.

Thanks a bunch @nhaouari 😃 
_William_

**Comment by nhaouari** [comment]
You're welcome.
