### ISSUE TITLE
Q: How I get a text summary use the textgenerator plugin?

### ISSUE THREAD

**Issue by YIRU69** [nhaouari/obsidian-textgenerator-plugin#36]
Thanks for your share about the fuuny and useful plugin>
 
And I have a long article or long text and want to know the summary, and could the plugin work it?

**Comment by nhaouari** [comment]
You're welcome, could you please ask your question in [https://github.com/nhaouari/obsidian-textgenerator-plugin/discussions](https://github.com/nhaouari/obsidian-textgenerator-plugin/discussions).
