### ISSUE TITLE
Request failed, status 429

### ISSUE THREAD

**Issue by Galaxy1013** [nhaouari/obsidian-textgenerator-plugin#39]
Hi mate,  

first of all, thanks for this great plugin. It worked really well for me. However, today I faced this issue. When I try to generate text every time it shows me this error:

plugin:obsidian-textgenerator-plugin:32187 Error: Request failed, status 429
    at new t (app.js:1:699319)
    at Xb (app.js:1:699511)
    at app.js:1:700188
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)

Please, help to resolve this. Thanks a lot

**Comment by nhaouari** [comment]
Hi, 
Please check the following issues #14 #33

**Comment by Galaxy1013** [comment]
Alright, got it. My credits have expired because 3 months have passed of free trial. Now, I've got more credits and everything works. Thank you!
