### ISSUE TITLE
Bug: The Temperature kept coming back to Zero (0)

### ISSUE THREAD

**Issue by Liong1976** [nhaouari/obsidian-textgenerator-plugin#4]
The Temperature kept coming back to Zero (0) even though I have set it to 0.7.
![image](https://user-images.githubusercontent.com/88898230/156015173-90d8995f-333a-47f4-b23b-2d2ea5a911f6.png)

However, if I put one (1), the number doesn't change.
![image](https://user-images.githubusercontent.com/88898230/156015241-5c7293d6-2f5c-430b-b6a2-abf59748646b.png)

### Obsidian Version

0.13.24

### Installer Version

0.13.23

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

**Comment by nhaouari** [comment]
The bug is fixed in [v0.0.2](https://github.com/nhaouari/obsidian-textgenerator-plugin/releases/tag/0.0.2).

**Comment by Liong1976** [comment]
Thanks, @nhaouari!

**Comment by nhaouari** [comment]
> Thanks, @nhaouari!

You're welcome.
