### ISSUE TITLE
No Option Button in 0.0.10

### ISSUE THREAD

**Issue by MrChill** [nhaouari/obsidian-textgenerator-plugin#45]
Hi,
And thanks for the amazing tool!
Update 0.1.10 has no option field in obsidian.

**Comment by MrChill** [comment]
I don't know if the issue is just on my side, but I cannot insert an API-Key or change the settings for the plugin.

![image](https://user-images.githubusercontent.com/28844714/205859933-ac37d2e8-4807-4402-b72d-540c61151cc0.png)

**Comment by nhaouari** [comment]
If you're unable to find the option field for Update 0.1.10 in Obsidian, try just to click on another plugin and then click on Text Generator plugin. Or you can access the options from Obsidian Settings. 
![image](https://user-images.githubusercontent.com/9850722/205866644-eee5b409-1f62-4903-a5a4-222f562b832e.png)

**Comment by nhaouari** [comment]
Hi,

The plugin has been updated to version 0.1.12 and should be working now. If you have any further issues, please let me know.

Thank you,
