### ISSUE TITLE
[Bug] Command Palette "Set max_tokens" using "enter" auto-submits Popup

### ISSUE THREAD

**Issue by limex** [nhaouari/obsidian-textgenerator-plugin#47]
Obsidian 1.03 on MacOS

**Steps**:
* Open Command Palette with Command+P
* Type "Text" to highlight the Command "Text Generator: Set max_tokens"
* Press "Enter" Button

**Expected:**
* Popup Dialog shows to edit the max_tokens

**Observed:**
* Popup Dialog flashes for some milliseconds ;)
* (probably) saves the existing setting
* shows a toast in the upper right corner

![Screen Recording 2022-12-06 at 18 27 25 (1)](https://user-images.githubusercontent.com/1173039/205983042-b0ecfd10-6ed5-47aa-9253-1f50f237b656.gif)

**Remark:**
Option/Alt+1 opens the Popup Dialog without Problems

Thanks for the great plugin & 
BR Günther

**Comment by limex** [comment]
Hi, sorry, still the same issue.
Update, restarted, Forced Reload, Checked Console: is empty

**Comment by nhaouari** [comment]
The plugin has been updated to version 0.1.14, and I have added more delay between opening the model and listening to ''enter key'' (from 100ms, which works fine for me, to 500ms).

**Comment by limex** [comment]
Works now. Thanks.
