### ISSUE TITLE
Doesn't Timeout Failed API Queries

### ISSUE THREAD

**Issue by jsonallen** [nhaouari/obsidian-textgenerator-plugin#49]
With the surge of new users, OpenAPI is frequently timing out on API requests.  The plugin doesn't seem to gracefully handle timeouts or other errors from OpenAPI.  Please see the attached screenshot.   I invoked a text generation action and then waited a couple of minutes with no output.  Subsequent text generation calls fail with "There is another generation process"

<img width="575" alt="Screen Shot 2022-12-07 at 12 03 56 PM" src="https://user-images.githubusercontent.com/1411223/206244517-5d09e0ae-6c79-40cb-8047-25730fd881b4.png">

**Comment by juestchaos** [comment]
+1 for this

**Comment by adrianghnguyen** [comment]
I think it would be nice if we had an option to manually terminate the request.

**Comment by nhaouari** [comment]
@jsonallen 
The latest version of our plugin includes a timeout parameter that can be adjusted in the settings, allowing for greater control and customization.

![image](https://user-images.githubusercontent.com/9850722/234214821-fb831eb1-75a1-4230-973a-c5bfeccd1ed3.png)

**Comment by dhjallen** [comment]
Fantastic.  Thank you!
