### ISSUE TITLE
Dear Community,   I don't know how to fix this error. I ask for your support. Maybe it is an API error? 

### ISSUE THREAD

**Issue by emincomikal** [nhaouari/obsidian-textgenerator-plugin#54]
<img width="746" alt="Bildschirm­foto 2022-12-13 um 10 34 06" src="https://user-images.githubusercontent.com/120456977/207280908-db7bef50-117e-4666-bb73-4be79e2632f6.png">

**Comment by nhaouari** [comment]
Hi,
Please check the following issues #9  #14  #28 #39

**Comment by emincomikal** [comment]
Thank you @nhaouari! It works now.

**Comment by emincomikal** [comment]
big thanks for your work!!
