### ISSUE TITLE
Please provide a valid frontmatter!

### ISSUE THREAD

**Issue by Klaudioz** [nhaouari/obsidian-textgenerator-plugin#6]
I'd like to know if I'm doing something wrong:

Every time I tried to use **Text Generator: Generate Text (Use Metadata))!** I got this:
![image](https://user-images.githubusercontent.com/632625/164083376-84326753-64ee-4490-9c81-c5f5b69a8918.png)

I got the same if I select everything and it works well if I use **Text Generator: Generate Text**

Looking at the source code, I can see that it's not getting the metadata correctly: https://github.com/nhaouari/obsidian-textgenerator-plugin/blob/fa25cb48b4994066559a16cac56591debf6ea1ee/main.ts#L113

**Comment by nhaouari** [comment]
When the frontmatter does not exist or it is not well formated this error is raised this is the case where `metadata.length === 0` . I think you should update obsidian to the latest version and try again.  

If you want to check manually the frontmatter, in the developer mode (ctrl+shift+i), run the following command 
`app.metadataCache.getCache(app.workspace.getActiveFile().path);` , you should see the frontmatter like this: 

```json
{
    "sections": ..
    ],
    "frontmatter": {
        "title": "Obsidian + Text Generator Plugin: The More Affordable and Powerful AI Text Assistante Helper",
        "keywords": [
            "AI Text Assistante Helper",
            "text assistant helper",
            "Jasper"
        ],
        "position": {
            "start": {
                "line": 0,
                "col": 0,
                "offset": 0
            },
            "end": {
                "line": 6,
                "col": 3,
                "offset": 181
            }
        }
    }
}
```

**Comment by Klaudioz** [comment]
If worked after updating Obsidian from version v0.14.2 to v0.14.6.

Thank you.
