### ISSUE TITLE
Error: Request failed, status 429

### ISSUE THREAD

**Issue by AdraVR** [nhaouari/obsidian-textgenerator-plugin#61]
Hello,
When I try to generate text, there are these 3 errors in the console, no matter which model I choose. 
Do you have any idea what is going wrong?

<img width="880" alt="Screenshot 2022-12-18 at 13 49 18" src="https://user-images.githubusercontent.com/75984619/208299409-4143d88b-5ce5-4c5e-a021-b2ecaac5c691.png">

_I obviously revoked the API key before posting this message_

**Comment by nhaouari** [comment]
Hello,
Please check the following issues https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/9 https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/14 https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/28 https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/39
