### ISSUE TITLE
Plugin broken 

### ISSUE THREAD

**Issue by stoettner** [nhaouari/obsidian-textgenerator-plugin#65]
Dear all,

as of today the plugin seems to be broken. 
Remediation steps done to no avail:
* de-install, re-install
* renew API key

Any idea?

I enjoy the plugin very much, hence would be awesome should you be able to have a look at it.

ton of thanks,
wolfgang

<img width="417" alt="screen_grap 2022-12-20 at 15 03 21" src="https://user-images.githubusercontent.com/15956536/208685492-ed2ce6f5-d2fa-4620-aca3-a6d3fd4da434.png">

**Comment by nhaouari** [comment]
Could you please try opening the Developer Tools console (Ctrl+Shift+i) and seeing if there are any errors being displayed there?

**Comment by stoettner** [comment]
Hi nhaouari,

Obsidian today updated to v1.1.8, post which text generator plugin resumed to work again.
Ton of thanks for getting back anyways.

reg
wolf

On 20. Dec 2022, at 15:12, nhaouari ***@***.***> wrote:


Could you please try opening the Developer Tools console (Ctrl+Shift+i) and seeing if there are any errors being displayed there?
