### ISSUE TITLE
Differentiate between Instruction and Completion?

### ISSUE THREAD

**Issue by chrisgrieser** [nhaouari/obsidian-textgenerator-plugin#69]
First of all, thank you so much for the plugin!

Consider the following three scenarios:
1. I have some text, and want the AI to complete the text, for example finishing a sentence I started.
2. I have an instruction, and want the AI to write text based on that prompt, for example "outline a blogpost about x"
3. I have text *and* an I have an instruction, for example "rewrite that sentence, but in simpler language"

How exactly do I use the plugin for these different scenarios? Experimenting with the plugin a bit, it seems that even the basic "generate text" command covers all three cases, depending on how I phrase the input text. But to me, it feels like having three commands for the three different scenarios would make this far more intuitive and also more clear in case of what happens in scenario 3.

**Comment by jvsteiner** [comment]
I second this idea.  In my case, I like to use the model to proofread or rewrite sections of text in a clearer or simpler way.  Basically the same use case as @chrisgrieser mentioned: "rewrite that sentence, but in simpler language".  

Perhaps a more generalized way to accomplish these types of uses would be to include a user configurable list of prefaces to prompts.  The effect would be, for example, turn a prompt from:

What are the historical origins of anti-war thought and sentiment?

to:

rewrite the following: "What are the historical origins of anti-war thought and sentiment?" 

These could be user configurable, for example, the users template would be:

Rewrite:
rewrite the following: "%text%" 

the generate command would apply the template, substituting the selected text for %text% before calling the API.

**Comment by jvsteiner** [comment]
And then I discovered that this already exists, and is awesome... 🤦

**Comment by nhaouari** [comment]
I am confident that all of the suggested features can be implemented using the template engine available in the latest version of the plugin, which is why I am closing this issue.
