### ISSUE TITLE
[Feature Request] Allow to select/set/use custom model nams

### ISSUE THREAD

**Issue by akaalias** [nhaouari/obsidian-textgenerator-plugin#7]
Hey there! Thank you for putting this plugin together. 

Since I mostly use my own trained models, could you possibly add an option to select (or simply provide a textfield for the name) for using a custom model?

That would be amazing! Thank you.

**Comment by nhaouari** [comment]
Hey,
Thank you for your suggestion. I am currently working on making the options more flexible through the frontmatter. This way, you will be able to override them easily and hopefully use your own models.

**Comment by arminta7** [comment]
> Since I mostly use my own trained models,

Are you training the models on your notes?

**Comment by Comprehensive-Jason** [comment]
Being able to use other models like GPT-J and GPT-Neo would be awesome!

**Comment by nhaouari** [comment]
In version 0.1.0 #22, You can update the models from OpenAI, and configure Body parameters or Request parameters through YMAL (The documentation not yet available. I am still working on it).
