### ISSUE TITLE
[feature request] Support for the Editing endpoints/models

### ISSUE THREAD

**Issue by phillipjohnston** [nhaouari/obsidian-textgenerator-plugin#72]
Given the Obsidian context, I think it would be awesome to be able to select the editing endpoints/models (potentially with a different command?)

> The [edits](https://beta.openai.com/docs/api-reference/edits) endpoint can be used to edit text, rather than just completing it. You provide some text and an instruction for how to modify it, and the `text-davinci-edit-001` model will attempt to edit it accordingly. This is a natural interface for translating, editing, and tweaking text. This is also useful for refactoring and working with code. Visit our [code guide](https://beta.openai.com/docs/guides/code/editing-text) to learn more. During this initial beta period, usage of the edits endpoint is free.

**Comment by nhaouari** [comment]
To achieve this, you can utilize the frontmatter configuration feature, more information is in the following link: http://text-gen.com/frontmatter-configuration.

**Comment by phillipjohnston** [comment]
Many thanks @nhaouari!

**Comment by phillipjohnston** [comment]
Hm, I might be missing something, but on that page I'm not seeing how I should hook up the editing model. Any tips?
