### ISSUE TITLE
Does chatgpt support

### ISSUE THREAD

**Issue by 0xtaosu** [nhaouari/obsidian-textgenerator-plugin#76]

**Comment by dev-msp** [comment]
There's no official API for ChatGPT, only the website. Plus they've added a lot of security to it to prevent abuse, so it's difficult to use it outside of the browser. I'm not the maintainer, but I would guess that it's not a good fit for this plugin.

**Comment by pdworkman** [comment]
Text Generator uses the same model (davinci 3) as ChatGPT, so you can get it to do most of the things that ChatGPT does (without the filters and fences) if you prompt it correctly.

**Comment by Quorafind** [comment]
Here is the official ChatGPT API: https://github.com/acheong08/ChatGPT/tree/1.0.1#official-api-browserless-token-required-paid

**Comment by nhaouari** [comment]
The official API for ChatGPT is available starting from version 0.2.x (gpt-3.5-turbo).
