### ISSUE TITLE
Problem with frontmatter

### ISSUE THREAD

**Issue by Falerion-git** [nhaouari/obsidian-textgenerator-plugin#8]
Hi,

If I try to use any frontmatter input, I always get the error message "Please provide a valid frontmatter!"

I tried to open a fresh vault (obsidian version 0.14.15) with only the textgenerator plugin installed (version 0.0.8), but the error persisted.
The used input used was just:

```
---
title: "How to write a youtube video"
---

Brain storming ideas 
```

Generating text with just selecting it, works fine.

**Comment by nhaouari** [comment]
Hi, I think you need to update obsidian, check the following issue : #6

**Comment by noheton** [comment]
Installed Obsidian v0.15.6 + TextGenerator 0.0.8

`app.metadataCache.getCache(app.workspace.getActiveFile().path);`
looks like this
```
{
    "sections": [
        {
            "type": "yaml",
            "position": {
                "start": {
                    "line": 0,
                    "col": 0,
                    "offset": 0
                },
                "end": {
                    "line": 3,
                    "col": 3,
                    "offset": 177
                }
            }
        },
        {
            "type": "paragraph",
            "position": {
                "start": {
                    "line": 5,
                    "col": 0,
                    "offset": 179
                },
                "end": {
                    "line": 5,
                    "col": 19,
                    "offset": 198
                }
            }
        },
        {
            "type": "paragraph",
            "position": {
                "start": {
                    "line": 7,
                    "col": 0,
                    "offset": 200
                },
                "end": {
                    "line": 7,
                    "col": 35,
                    "offset": 235
                }
            }
        },
        {
            "type": "paragraph",
            "position": {
                "start": {
                    "line": 9,
                    "col": 0,
                    "offset": 237
                },
                "end": {
                    "line": 9,
                    "col": 17,
                    "offset": 254
                }
            }
        }
    ]
}
```
no "frontmatter" property.

my markdown document looks like this:
```
---
title: "Obsidian + Text Generator Plugin: The More Affordable and Powerful AI Text Assistant Helper"
keywords: [AI Text Assistant Helper, scientific writing, citations]
---

Write introduction 

Write about problems with citations

Write conclusion 
```

**Comment by atomical** [comment]
Getting the same issue on the latest version of Obsidian that I just installed.

**Comment by nhaouari** [comment]
If you are receiving an error message that states "Please provide a valid frontmatter!" it means that your frontmatter is not correctly formatted. This issue is not related to the plugin.

We recommend that you copy and paste the example from the Readme using CTRL+SHIFT+V to avoid pasting it as code which might the source of the issue. 

The following link explains very well using YMAL in obsidian [YAML front matter](https://help.obsidian.md/Advanced+topics/YAML+front+matter)
