### ISSUE TITLE
Request failed, status 503

### ISSUE THREAD

**Issue by valiantgenomics** [nhaouari/obsidian-textgenerator-plugin#80]
First of all, thanks a TON for developing this brilliant plugin! I really appreciate your selfless, hard work!

I'm getting this Request failed, status 503 error.

![image](https://user-images.githubusercontent.com/111633318/211171217-07dc8db9-fd5e-40f7-9a1f-d3f4546a4453.png)

I did check the already existing issues here, #9 #14 #28 #39

I do have a lot of credits in my OpenAI account, so that's not an issue.

My API is integrated correctly.

The text-generator plugin worked perfectly fine 2-3 weeks ago. Not sure if some sort of an update crashed it but I'm getting other errors as well. But this 503 error is most prevalent, that's why I'm posting it here.

I'm not getting rate-limited because I'm only trying to generate 200-300 words at once.

Thank you again for your time and efforts! Highly highly appreciated!

BTW, I'm on Linux Pop!_OS 22.04 LTS x86_64

**Comment by nhaouari** [comment]
I think it is an OpenAI API issue. check the following post [https://community.openai.com/t/status-code-503-that-model-is-currently-overloaded-with-other-requests/31433](https://community.openai.com/t/status-code-503-that-model-is-currently-overloaded-with-other-requests/31433).
