### ISSUE TITLE
[Error] Links not beeing included in prompt

### ISSUE THREAD

**Issue by pheelwell** [nhaouari/obsidian-textgenerator-plugin#81]
With "includeChildren" enabled I would expect the prompt to include the text of the internal link:
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/57875510/212196394-929b8082-c769-4fb5-8a59-552392626781.png">
But instead i don't see the actual content of the linked document  getting appended:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/57875510/212196188-b8ca7381-09ea-433f-b9ef-7566948e6dc1.png">
Which results in the generated text not including the information I want to provide:
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/57875510/212196502-a1e23d7d-c25f-4bda-87e2-d0a41971c654.png">
Do I misunderstand the includeChildren Feature, or is this intended to work?

**Comment by nhaouari** [comment]
children  can be used as in a template. To use it, create a similar template and apply it
```md
---
PromptInfo:
 id: brainstormChildren
 name: 🗞️ brainstorm ideas about children
 description: 
 author: Noureddine
 tags: testing
 version: 0.0.1
---
context: 
{{#each children}}
{{this.content}}
{{/each}}

prompt:
brainstorm ideas about context
Ideas: 
* 

```

**Comment by pheelwell** [comment]
Thank you for clarifying, I missed that this was only applied to templates.
