### ISSUE TITLE
Error:Text Generator Plugin:Error check console CTRL+SHIFT+I

### ISSUE THREAD

**Issue by ajmz** [nhaouari/obsidian-textgenerator-plugin#90]
Error:Text Generator Plugin:Error check console CTRL+SHIFT+I

![2023-02-01_095456](https://user-images.githubusercontent.com/30185045/215926790-a0f1480d-e8fb-4038-81f8-cd40e7795a2f.png)

**Comment by pdworkman** [comment]
Open your console and see what error it is giving you.

**Comment by ajmz** [comment]
> Open your console and see what error it is giving you.

Error: Request failed, status 429.
I found the same issues before.
Thanks.

**Comment by pdworkman** [comment]
Check your credits on your OpenAI account.

**Comment by YIRU69** [comment]
> Check your credits on your OpenAI account.

I have the same issue. And check my credits have no problem. Could you help me plz

**Comment by pdworkman** [comment]
I have gotten it a few times in the last couple of weeks. Sometimes, there does not seem to be anything wrong on my end, and I think that OpenAI servers have just been lagging/overtaxed. Sometimes if I try it again a second time, it works, or if I wait a minute or two and try again. That tells me it is either their servers or it is my internet connection being flaky.

The other problem that I have run into lately is if my tokens are not set high enough or I am submitting too much text in the request. This is not likely your problem unless you are sending 1500+ words at a time ("summarize this chapter" for example). But OpenAI does seem to have cut back on how much it will process at once even if your tokens are set high enough. Someone told me that they have changed the way they are calculating tokens in the last couple of weeks, but I don't know if that is true.

**Comment by TerrificTerry** [comment]
I have met the same issue before, and I guess turning down the max tokens will help. There might be some issues with the api key if too much token is required to be processed in one answer, and keeping the value under 1024 will solve the problem.
