### ISSUE TITLE
Too much input?

### ISSUE THREAD

**Issue by pdworkman** [nhaouari/obsidian-textgenerator-plugin#92]
The last few days, I have started getting the error status 400 when I have a large amount of text selected for the input. This is a change, because I was able to get it to accept full chapters before ("summarize this chapter" or "critique this chapter") and now it doesn't seem to want to accept more than 1000-1500 words of input at a time. Has something change with the way OpenAI is calculating tokens? Or are they clamping down on how much you are allowed to do at a time? Do I just keep increasing my tokens or only submitting half chapters at a time?

**Comment by nhaouari** [comment]
The token count of your prompt plus max_tokens cannot exceed the model's context length. Most models have a context length of 2048 tokens (except for the newest models , which support 4096).

![image](https://user-images.githubusercontent.com/9850722/216415902-039810ba-2675-4d2a-86c5-6073b5bb8e13.png)
https://platform.openai.com/docs/api-reference/completions
