### ISSUE TITLE
Feature request: Generate note title

### ISSUE THREAD

**Issue by ClandestineClout** [nhaouari/obsidian-textgenerator-plugin#97]
ChatGPT did an awesome job at this for my use case. I frequently open a new note and don't know what to name it until later. I have hundreds of untitled notes in my vault for various reasons, and I can't be bothered to go through each one by one and naming them myself.

A command to quickly generate and name notes (or offer some name suggestions) based on the contents of the note would be amazing.

**Comment by nhaouari** [comment]
I appreciate your feedback and will consider the possibility of implementing the suggested feature in a future release of Text Generator Plugin. 
 Thank you for taking the time to share your thoughts with us and for your support

**Comment by nhaouari** [comment]
Check the new version of the plugin 0.2.0 where a new command is introduced to generate a title for the active note.
