### ISSUE TITLE
display “Error” in recent days

### ISSUE THREAD

**Issue by jhougomont** [nhaouari/obsidian-textgenerator-plugin#99]
### Discussed in https://github.com/nhaouari/obsidian-textgenerator-plugin/discussions/95

<div type='discussions-op-text'>

<sup>Originally posted by **cgofun** February 11, 2023</sup>
![Screenshot_20230212_101928_md obsidian_edit_477168564829793](https://user-images.githubusercontent.com/7732886/218289432-083c3c66-7a23-443e-ba10-e196e402197d.jpg)

![Screenshot_20230212_112524_com microsoft rdc android_edit_484388633258](https://user-images.githubusercontent.com/7732886/218291281-ed677704-86ca-4201-acc1-2dd1ecd0a484.jpg)

Same on PC and mobile phone. How to solve it？</div>

**Comment by yaqlee** [comment]
I come up with same problem.. waiting for solution...

**Comment by jhougomont** [comment]
I found the solution. You have to register with a Credit Card, even if you're not going to exceed the $18 initial allowance. Once I did that (and waited about 15 minutes for the servers to update), I was able to use the plugin as described.

**Comment by niecailong** [comment]
> I found the solution. You have to register with a Credit Card, even if you're not going to exceed the $18 initial allowance. Once I did that (and waited about 15 minutes for the servers to update), I was able to use the plugin as described.

When I registered, I only used the mailbox and phone number. Do you mean to buy Plus?
